### ISSUE TITLE
What happens when a doublet cluster is present in the clustering ?

### ISSUE THREAD

**Issue by Fougere87** [chris-mcginnis-ucsf/DoubletFinder#1]
Hi, 
Thank you for your work, I'm testing it right now ! I'm working on a huge 10X single cell dataset and it seems doublets will be an issue to caracterize cell populations.. 
But I was wondering about one thing with your approach : in my dataset, whatever clustering approach I use, it obtain what may be a doublet cluster, certainly containing cells from the two known major populations in my samples. Don't you think it might interfere with doubletFinder as it will create synthetic doublets with doublets from the cluster and other valid cells ?
Thanks !

**Comment by chris-mcginnis-ucsf** [comment]
Hello!

You make a very good point. We thought about this a lot in the early stages of this project. It is certainly possible to generate artificial doublets using a subset of cells that are high-confidence singlets. However, choosing these subsets is not possible for all biological systems (i.e., where marker genes are unknown), and could lead to the introduction of user-defined sources of bias in the results. Since we sought to develop the most widely-applicable method for doublet detection, we opted for completely random sampling of existing datasets during artificial doublet generation.

Moreover, it is worth considering that real doublets are (1) less frequent than singlets in most scRNA-seq datasets and (2) tend to have greater nUMIs. For these reasons, the proportion of artificial doublets that are made using real doublets will be in the minority and will likely remain close to their original high-density doublet region in PC space. 

Chris

**Comment by Fougere87** [comment]
Hi, 
Thank you for your answer, yes I trully agree with your point, it's better this way and quite reproducible. Moreover, I gave a try to doubletFinder on a dataset of 10000 cells and happily, the predicted "doublets" were in majority in the cluster we hypothesized  to be doublets ! So it's quite satisfying for now !
I'm right now trying doubletFinder at a bigger scale with merged samples to see if there is a good reproducibility when running on one capture of cells or 10 of them for example. 
I think an interesting improvement would be the possibility to keep the synthetic doublets somewhere along with the information about their origins of this doublet. With that it may be possible to "trace" the origin of the real doublets using there similarity with the synthetic ones... And then look if there is some bias in the proportions for example. 
Best, 
Chloé

**Comment by huuthoth** [comment]
Hi,
Could you provide the code you used in fig. 2E?
Thanks

**Comment by dkqwert96** [comment]
Hi Chris, 

Thanks for your tool!
I have a Cell Hashing dataset and I get this error when I try to run summarizeSweep. 
What could be the problem?

`> gt.calls <- c1.c2.object.filtered@meta.data[rownames(sweep.res.list_c1.c2[[1]]), "HTO_classification.global"] 
> sweep.stats_c1.c2 <- summarizeSweep(sweep.res.list_c1.c2, GT = TRUE, GT.calls = gt.calls)
Error in .performance.auc(fpr.stop = 1, predictions = c(`1` = 0.879533925266824,  : 
  Not enough distinct predictions to compute area under the ROC curve.`

Also, do you mind sharing the code you used for the Cell Hashing data?



> I ended up defining homotypic doublets in a better way in the published manuscript. This figure was created by tracking which doublets were defined from cells with the same cell type annotation (which is inherently flimsy, because cell type annotations are user-defined).
> 
> In the paper, I instead defined homotypic doublets as real (i.e., demuxlet-defined) doublets that had similar proportions of doublet neighbors in PC space as real singlets. These results are shown in figure 1F and S2A for the Demuxlet and Cell Hashing datasets, respectively.
> 
> Find code for the demuxlet data below:
> 
> ```r
> ## Demuxlet ------------------------------------------------------------------------------------------------
> # Compute PC distance matrix
> PCs <- seu_demux@calc.params$RunTSNE$dims.use
> pca.space_demux <- seu_demux@dr$pca@cell.embeddings[,PCs]
> pca.dist.mat_demux <- fields::rdist(pca.space_demux)
> 
> # Find each cell's nearest neighbors
> for (i in 1:nrow(pca.space_demux)) { pca.dist.mat_demux[, i] <- order(pca.dist.mat_demux[, i]) }
> 
> # Determine proprtion of real doublets amongst each cell's k nearest neighbors
> neighbor.info_demux <- as.data.frame(matrix(0L, nrow=nrow(pca.dist.mat_demux), ncol=2))
> colnames(neighbor.info_demux) <- c("Demuxlet","pDoublet")
> rownames(neighbor.info_demux) <- rownames(pca.space_demux)
> neighbor.info_demux$Demuxlet <- seu_demux@meta.data$Demuxlet
> 
> k <- round(nrow(neighbor.info_demux)*0.01)
> for (i in 1:nrow(pca.space_demux)) {
>   neighbors <- pca.dist.mat_demux[2:(k+1), i]
>   neighbor.info_demux$pDoublet[i] <- length(which(neighbor.info_demux[neighbors,1] == "Doublet"))/k
> }
> 
> # Find intersection of singlet and doublet density estimations -- real doublets below threshold = homotypic
> gkde.singlet <- approxfun(bkde(neighbor.info_demux$pDoublet[which(neighbor.info_demux$Demuxlet == "Singlet")], kernel="normal"))
> gkde.doublet <- approxfun(bkde(neighbor.info_demux$pDoublet[which(neighbor.info_demux$Demuxlet == "Doublet")], kernel="normal"))
> x <- seq(from=min(neighbor.info_demux$pDoublet), to=max(neighbor.info_demux$pDoublet), length.out=nrow(neighbor.info_demux))
> poi <- which(diff(gkde.singlet(x) > gkde.doublet(x)) != 0); thresh_demux <- x[poi] 
> print(length(which(neighbor.info_demux$Demuxlet == "Doublet" & neighbor.info_demux$pDoublet <= thresh_demux)) / length(which(neighbor.info_demux$Demuxlet == "Doublet")))
> 
> ## Plotting ~ pDoublet density plot (300x250)
> ggplot(data=neighbor.info_demux, aes(x=pDoublet, fill=Demuxlet)) + geom_density(alpha=0.5) + 
>   scale_fill_manual(values=c("red","black")) + geom_vline(xintercept = thresh_demux, linetype="dashed") +
>   theme(legend.position = "none")
> 
> ## Plotting ~tSNE w/ homo + hetero distinguished
> temp <- as.character(neighbor.info_demux$Demuxlet)
> temp[which(neighbor.info_demux$Demuxlet == "Doublet" & neighbor.info_demux$pDoublet <= thresh_demux)] <- "Homotypic"
> temp[which(temp == "Doublet")] <- "Heterotypic"
> seu_demux@meta.data[,"HeteroHomo"] <- factor(temp, levels=c("Heterotypic","Homotypic","Singlet"))
> TSNEPlot(seu_demux, group.by="HeteroHomo", pt.size=0.5, vector.friendly=TRUE, colors.use = c("black","red","#E3E3E3"), no.legend=TRUE)
> TSNEPlot(seu_demux, group.by="HeteroHomo", pt.size=0.5, vector.friendly=TRUE, 
>          colors.use = c("#E3E3E3","black","red"), no.legend=TRUE, plot.order=c("Homotypic","Heterotypic","Singlet"))
> ```
