### ISSUE TITLE
error at "modelHomotypic"

### ISSUE THREAD

**Issue by wkkion** [chris-mcginnis-ucsf/DoubletFinder#10]
Hi,
     I was running the function "modelHomotypic". however, I got a error as follow:

homotypic.prop <- modelHomotypic(ctrl_doublet@ident)
Error in modelHomotypic(ctrl_doublet@ident) : object 's' not found

I wonder that what is the mean of object 's', and how to debug it.

**Comment by chris-mcginnis-ucsf** [comment]
Simple typo -- was 's' instead of '2'. Thanks for catching!
