### ISSUE TITLE
Which value is the cell loading density value?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [chris-mcginnis-ucsf/DoubletFinder#100]
Hi everyone, 

I hope to use DoubletFinder in my Seurat pipeline for scRNA-seq data from 3 donors of the same sorted cell population and cell type without any stimulation.

From various discussions, I understand the cell loading density is the density of cells loaded into the 10X microfluidics chip, used to sequence the data. This cell loading density value will correspond to an estimated doublet formation rate that is specific to my dataset. This rate is what we need to predict potential doublets.

However, when I looked at the outputs from the 10X Genomics Cell Ranger summary, I cannot seem to find this value. Any pointer? 

Thank you very much for your help!

<img width="916" alt="Screen Shot 2021-02-09 at 10 40 08 PM" src="https://user-images.githubusercontent.com/62179082/107438004-c486d780-6b27-11eb-9940-0f8189ab4add.png">

**Comment by chris-mcginnis-ucsf** [comment]
Hi again @denvercal1234GitHub ,

Looks like you loaded the 10x lanes to yield ~4500 cells/lane. According to the 10x protocol, this means you should expect about a 3.5% doublet rate. 

Chris
