### ISSUE TITLE
Filtering cells with too high nCount_RNA?

### ISSUE THREAD

**Issue by apredeus** [chris-mcginnis-ucsf/DoubletFinder#106]
Hello Chris, 

Thank you for the tool. I had a quick question after reading the README and doing a test run. 

Normal Seurat filtering often includes removal of genes with too high of a nCount_RNA - presumably, because they are doubles or multiplets, as a basic way of accounting for them. The filtering step in basic Seurat vignette is 

`pbmc <- subset(pbmc, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 5)`

I was wondering: this should not be done if proper doublet finding algorithm is ran, right? Algorithms seem to assume that doublet formation rate is dependent on the number of cell in one run. Thus, if we take 10,000 cells and expect 10% of them to be doublets, that means 1000 of them are. But if we remove all cells with very high nFeature_RNA (say, highest 500), then the remaining set contains only 500 true doublets. But our modelling, on the other hand, will take 9,500 cells and expect about 950 of them to be doublets. Does that sound right? 

Additionally, I have to say, the description here (quoting the readme) is unclear. What are low-quality cell clusters and "uninformative marker genes"? 

> Ensure that input data is cleared of low-quality cell clusters. There are a variety of ways to do this, but I usually use the following workflow:
> 
> Manually threshold raw gene expression matrices according to RNA nUMIs (especially important when dealing with super-loaded 10X data because of the way CellRanger threholds data -- See Lun et al., 2019, Genome Biology.
> Pre-process data using standard workflow.
> Identify clusters with (A) low RNA UMIs, (B) High % mitochondrial reads, and/or (C) Uninformative marker genes.
> Remove clusters, pre-process again, and run DoubletFinder.

**Comment by apredeus** [comment]
Sorry to bother, but could you please comment on this?

**Comment by chris-mcginnis-ucsf** [comment]
Hi @apredeus -- Apologies for the extremely slow response. As for your questions:

"I was wondering: this should not be done if proper doublet finding algorithm is ran, right?"

Correct. I would not remove high nUMI cells, as this will cause deviations in your doublet number estimate used to threshold pANN. 

"What are low-quality cell clusters and "uninformative marker genes"?"

Low-quality cell clusters are clusters with low total RNA UMIs, high % mitochondrial UMIs, and uninformative marker genes. Uninformative marker genes are usually ribosomal or housekeeping genes.

Chris
