### ISSUE TITLE
subset doesn't work while extracting "Singlet" found by Doubletfinder

### ISSUE THREAD

**Issue by Statekeylablin** [chris-mcginnis-ucsf/DoubletFinder#107]
Hi,
Thanks for your work on finding doublets. I attempt to run Doubletfinder for sixteen samples at the same time. However, different samples got different optimal parameters. Therefore, the final column names of the classification results are different, such as 
DF.classifications_0.25_0.16_859, DF.classifications_0.25_0.18_867......I want to subset the data in a parallel way, see below please
![屏幕快照 2021-03-12 下午5 55 15](https://user-images.githubusercontent.com/49443927/110924044-89610980-835c-11eb-885c-f2b1ada015e3.png)

I don't know how to operate on it. Looking forward to your reply.
                                                                                                           Lin

**Comment by guanxn90** [comment]
> Hi,
> Thanks for your work on finding doublets. I attempt to run Doubletfinder for sixteen samples at the same time. However, different samples got different optimal parameters. Therefore, the final column names of the classification results are different, such as
> DF.classifications_0.25_0.16_859, DF.classifications_0.25_0.18_867......I want to subset the data in a parallel way, see below please
> ![屏幕快照 2021-03-12 下午5 55 15](https://user-images.githubusercontent.com/49443927/110924044-89610980-835c-11eb-885c-f2b1ada015e3.png)
> 
> I don't know how to operate on it. Looking forward to your reply.
> Lin

Hi Lin, after running each single sample, perhaps rename (or duplicate a new column) the column of Df.classification.x.x.x) to be a consistent name (like DF.DoubletFinder). Then all sample will have the consistent name.

**Comment by Statekeylablin** [comment]
Thank you.
