### ISSUE TITLE
Removal of a minor cell population by DoubletFinder

### ISSUE THREAD

**Issue by apredeus** [chris-mcginnis-ucsf/DoubletFinder#108]
Hello Chris, 

I've discovered a potentially problematic behaviour by `DoubletFinder` and was wondering if you'd be interested in debugging it. I'm putting together an intro notebook for our users at Sanger, and used a bigger dataset to demonstrate doublet removal. I ended up using [10k PBMC cells from 10X Genomics](https://support.10xgenomics.com/single-cell-gene-expression/datasets/4.0.0/SC3_v3_NextGem_DI_PBMC_10K). 

Basically, `DoubletFinder` with the expected doublet formation rate of 7.6% (I got it from the 10x table) runs smoothly and identifies few clusters of doublets. Problem is, one of these clusters is a small cluster of dendritic cells (there's about 20-30 cells in the whole dataset) that is marked as doublets completely and is removed. Same processing with `scrublet` does not result in this (and marks fewer cells - something on the order of 550). 

I'd be happy to provide the reproducible example (it would be a bit too much code to paste here). Let me know if you'd be interested in looking into this problem.

**Comment by batalha23** [comment]
Hi, I would be interested in a reply to this issue as well as I'm observing the same in my dataset of 40k human PBMC. I can clearly see a small but discrete population of cDC before doublet removal, which completely disappears after running DoubletFinder.
Thank you!
