### ISSUE TITLE
Incompatible with Seurat 3.0

### ISSUE THREAD

**Issue by MaxKman** [chris-mcginnis-ucsf/DoubletFinder#11]
Hey,

thanks for developing doubletFinder. I find it really useful. 

The structure of Seurat objects changed with Seurat 3.0 and your function is currently incompatible with it. It returns "no slot of name "data" for this object of class "Seurat"". 

Best Max

**Comment by chris-mcginnis-ucsf** [comment]
Thanks for letting me know. I will get more familiar with Seurat V3 and adjust the code accordingly.

**Comment by MaxKman** [comment]
Great. I think it should be a quick fix. Essentially every call of seurat.object@data / @scale.data just needs to be replaced with seurat.object@assays$RNA@data / @scale.data.

**Comment by chris-mcginnis-ucsf** [comment]
Hey -- would you mind trying out these two new functions? I'm in the middle of reviews so do not want to deal with Seurat version control at the moment (still using V2 for the time being). These are the only two functions that access the raw.data or data slots of Seurat objects, so the others *should* be compatible with V3.


Chris



________________________________

**Comment by MaxKman** [comment]
Sure, where do I find them?

**Comment by chris-mcginnis-ucsf** [comment]
I attached to the previous email

On Dec 24, 2018, at 2:09 AM, MaxKman <notifications@github.com<mailto:notifications@github.com>> wrote:


Sure, where do I find them?

**Comment by MaxKman** [comment]
Sorry for the late response. Just checked again. I didn't receive any attachment to the email.

**Comment by abdallahamr** [comment]
Hi Chris 

I was also having the same issue when upgrading to seurat 3, I did try to run the functions you sent a couple of days ago and still getting the same error 

#####
Loading required package: fields
Error in doubletFinder_ParamSweep_v3(sce_so) : 
  no slot of name "calc.params" for this object of class "Seurat"
In addition: Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘fields’
#####

I understand you don't want to upgrade to seurat 3 atm but maybe you can save it in a different directory, just open a new Rstudio window and apply the following code so you can test it 

library(devtools)
library(withr)
with_libpaths(new = "/path/of/dir/", install_github(repo = 'satijalab/seurat', ref = 'release/3.0'))


######### and then when loading

library(Seurat,lib.loc = "/path/of/dir/")


Thanks a lot

**Comment by chris-mcginnis-ucsf** [comment]
Working this out now -- will have new code uploaded by end of the day today.

**Comment by abdallahamr** [comment]
Ok great, thank you, please let me know if I can be of help!

**Comment by chris-mcginnis-ucsf** [comment]
Just uploaded two new functions -- 'doubletFinder_V3' and 'paramSweep_V3' that are compatible with Seurat V3. Usage is the same as original functions, and I've reproduced the paper results with the Demuxlet data. 

Thanks to you all for bringing this to my attention! Closing the issue now.
