### ISSUE TITLE
The DoubletFinder bug display

### ISSUE THREAD

**Issue by honghh2018** [chris-mcginnis-ucsf/DoubletFinder#110]
Hi @Developer,
      Thanks to develop the great tool.
       The error was showing up seem like a bug when i take the DoubetFinder to filter the Doublet cell data.
       It was peculiar about this issue, because the  first couple of sample can work well using DoubletFinder, just one of sample getting below:
      
DoubletFinder: Error in h(simpleError(msg, call)): Error in evaluating the'x' parameter when selecting the method for the't' function: Missing values ​​cannot be used where TRUE/FALSE values ​​are required Calls: RunDF ... resolve.list -> signalConditionsASAP -> signalConditions
![image](https://user-images.githubusercontent.com/41668708/118954666-90c21600-b990-11eb-8766-e7e58e4f0ee5.png)

So how can i fix this issue?
 Best,
hanhuihong

**Comment by honghh2018** [comment]
The code showing below:
  sweep.res.list_kidney <- paramSweep_v3(before_rds, PCs = 1:PCs, sct = T)
     sweep.stats_kidney <- summarizeSweep(sweep.res.list_kidney, GT = FALSE)
     bcmvn_kidney <- find.pK(sweep.stats_kidney)
     mpK<-as.numeric(as.vector(bcmvn_kidney$pK[which.max(bcmvn_kidney$BCmetric)]))
  
     # 找最佳 nExp
     annotations <- before_rds@meta.data$seurat_clusters
     homotypic.prop <- modelHomotypic(annotations)
     nExp_poi <- round(ratio*ncol(before_rds@assays$RNA@data))
     nExp_poi.adj <- round(nExp_poi*(1-homotypic.prop))
  
     doublet_filter <- doubletFinder_v3(before_rds, PCs = 1:PCs, pN = pN, pK = mpK, nExp = nExp_poi, reuse.pANN = FALSE, sct = T)

**Comment by chris-mcginnis-ucsf** [comment]
Hi @honghh2018 -- apologies for the slow response.

I've never seen this error -- were you able to troubleshoot?

Chris

**Comment by honghh2018** [comment]
Hi Chris,
     I am afraid not, This error is look like a knerl code that i can not figure it out myself.
     Hope  you help to solve that.
     If anything you need, let me know.
Best,
Hanhuihong

**Comment by chris-mcginnis-ucsf** [comment]
Since you had DoubletFinder work before and since nobody has posted this same error (also, to selfishly save myself time), I'd appreciate if you tried it again after starting the analysis from scratch (i.e., raw gene expression count matrices). If the same error pops up, please reach out again.
