### ISSUE TITLE
doubletFinder_v3 - Finding variable genes...

### ISSUE THREAD

**Issue by yeetingc** [chris-mcginnis-ucsf/DoubletFinder#114]
Hi,

I wonder if anyone has this error before.

[1] "Finding variable genes..."
Error in FindVariableFeatures.Assay(object = assay.data, selection.method = selection.method,  : 
  Both 'mean.cutoff' and 'dispersion.cutoff' must be two numbers

I also used the code to check if they are numeric and the results were TRUE
!is.na(as.numeric(split_seruat_ctrl@commands[["FindVariableFeatures.SCT"]]@params[["dispersion.cutoff"]]))
!is.na(as.numeric(split_seruat_ctrl@commands[["FindVariableFeatures.SCT"]]@params[["mean.cutoff"]]))

Could anyone think of any possibilities? Thank you!

**Comment by Bioerjzy** [comment]
Hi, did you fix this? I ran into the same error.

**Comment by bobermayer** [comment]
I tried to use it on a scTransform-normalized object but ran into #115. I then did `NormalizeData` and ran into this issue. So I added `FindVariableFeatures` and `ScaleData` before the DoubletFinder calls, then it failed with `Error in if (rev.pca) { : argument is of length zero` in the PCA step. So I also added `RunPCA()`, and now works (this is `DoubletFinder_2.0.3` so maybe obsolete)
