### ISSUE TITLE
Error in doubletFinder_ParamSweep

### ISSUE THREAD

**Issue by huyuem** [chris-mcginnis-ucsf/DoubletFinder#12]
Hi,

Thanks for developing doubletFinder. It's really useful.

When I use "doubletFinder_ParamSweep" to identification pK, it shows errors.

An example of the bottom of the output file when errors are encountered is shown below.

> sweep.res.list_pbmc4k <- doubletFinder_ParamSweep(pbmc4k_0.6)
[1] "Creating artificial doublets for pN = 5%"
[1] "Creating Seurat object..."
[1] "Normalizing Seurat object..."
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
[1] "Finding variable genes..."
Calculating gene means
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating gene variance to mean ratios
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
[1] "Scaling data..."
Scaling data matrix
  |======================================================================| 100%
[1] "Running PCA..."
[1] "Calculating PC distance matrix..."
[1] "Defining neighborhoods..."
[1] "Computing pANN across all pK..."
[1] "pK = 5e-04..."
Error in `row.names<-.data.frame`(`*tmp*`, value = value) :
  invalid 'row.names' length

Best

**Comment by Reprobate** [comment]
I've experienced this issue as well. I've tried on a few data-sets and sometimes it works, but sometimes throws the error. I've noticed that it tends to throw the error on smaller data-sets (< 10,000 cells).

**Comment by chris-mcginnis-ucsf** [comment]
Hi @Reprobate and @huyuem -- I just unsuccessfully tried to recreate the error using the 10X 10K heart dataset (actually includes ~7K cells, so in theory should have triggered the error). So it doesn't seem to depend on cell number. Without your actual data, it will be hard for me to diagnose the issue -- Could you two provide some more information?

**Comment by katherinehuang14** [comment]
I have got the same issue and figured out what is wrong after went through your codes. The problem is:
length(seu@cell.names) != ncol(seu@raw.data) after you remove some cells by SubsetData or FilterCells.

**Comment by chris-mcginnis-ucsf** [comment]
Ah, okay! Thanks for looking into this. I made the following change, which should fix the issue:

## Down-sample cells to 10000 (when applicable) for computational effiency
  if (ncol(seu@data) > 10000) {
    real.cells <- colnames(seu@data)[sample(1:ncol(seu@data), 10000, replace=FALSE)]
    data <- seu@raw.data[ , real.cells]
    n.real.cells <- ncol(data)
  }
  
  if (ncol(seu@data) <= 10000){
    real.cells <- colnames(seu@data)
    data <- seu@raw.data[, real.cells]
    n.real.cells <- ncol(data)
  }
