### ISSUE TITLE
The find.pK function does not create a plot as it should

### ISSUE THREAD

**Issue by TereziaKurucova** [chris-mcginnis-ucsf/DoubletFinder#120]
Hi Chris.
Thank you for this amazing tool!
I'm struggling a bit with the find.pK function. When the function is called, the resulting  plot looks like this:
![Rplot08](https://user-images.githubusercontent.com/63232511/131656225-e17a0c23-0024-4ec6-aac9-fc0e9cbb2e20.png)

I guess some of my dependencies may be in the wrong version.
Could you please help me identify what is responsible for this and how can I fix it?
I'm attaching a list of dependency versions: 
- Seurat (4.0.4)
- Matrix (1.3-4)
- fields (12.5)
- KernSmooth (2.23-18)
- ROCR (1.0-11)
- parallel (4.0.4)

Many thanks
T.

**Comment by phoebee-h** [comment]
Hi, 
Not sure what do you mean by "wrong". I think it just not showed with the label and you can modify the figure with the table generated by `find.pK`. The x-axis should be "pK" and the y-axis should be "BCmvn" (where the column "BCmetric" represent this.)


```
## You will see this "bcmvn_kidney" is a dataframe with 5 columns, which are: ParamID, pK, MeanBC,  VarBC, BCmetric
bcmvn_kidney <- find.pK(sweep.stats_kidney)

## Note that the "pK" column could be a factor, so converted to character and then numeric might be necessary.
plot(x = as.numeric(as.character(bcmvn_kidney$pK)), y = as.numeric(bcmvn_kidney$BCmetric), pch = 16, col = "#41b6c4", cex = 0.75, xlab="pK", ylab="BCmetric")
lines(x = as.numeric(as.character(bcmvn_kidney$pK)), y = bcmvn_kidney$BCmetric, col = "#41b6c4")
```

P.S. I am not from the development team, just a user of DoubletFinder. 

Hope this helps!

**Comment by BiotechPedro** [comment]
Hi @chris-mcginnis-ucsf ! What do you mean by counting the dots? Are you talking respectively to the dots near to a maximum or the total number? Could you explain this in a deeper way? Thanks!
