### ISSUE TITLE
Separating different kinds of doublets

### ISSUE THREAD

**Issue by ekernf01** [chris-mcginnis-ucsf/DoubletFinder#127]
Hi Dr. McGinnis, I'm a big fan of this tool and I'd like to ask about a feature that would help me a lot in an overloaded 10X run with a large quantity and diversity of doublets. Given a user-provided set of cell type assignments, would it be possible to separately mark "doublets combining cell type 1 and cell type 2" from "doublets combining cell type 2 and cell type 3", et cetera? I'm not sure whether this feature exists, but it ought to be easy to add, and I would be willing to try and contribute a pull request.

**Comment by chris-mcginnis-ucsf** [comment]
Hi @ekernf01 ,

I implemented a version of this early on when developing DF and it definitely works, although I didn't end up including it in the final package. I'm not sure I'll end up including in the final package, but if you want to implement an addition to the 'doubletFinder_v3' function I'll give it a look.

**Comment by ekernf01** [comment]
Cool! I have added this feature.
