### ISSUE TITLE
pANN can correlate with Cycling. [Not an issue]

### ISSUE THREAD

**Issue by tiagobrc** [chris-mcginnis-ucsf/DoubletFinder#128]
Thanks for making this amazing tool!

I  just started learning about it and using the DoubletFinder and noticed a cool side effect of the pANN score that is its correlation with the cycling cells. Do you have any thoughts on that? 

<img width="894" alt="Screen Shot 2022-01-13 at 2 34 39 PM" src="https://user-images.githubusercontent.com/12516337/149398309-92f2f9dc-3b2d-4274-b9ce-9208ed803bb9.png">

<img width="891" alt="Screen Shot 2022-01-13 at 2 34 50 PM" src="https://user-images.githubusercontent.com/12516337/149398637-8eb71ace-bb19-4155-a17d-fa76a8b696b4.png">

Thanks

**Comment by chris-mcginnis-ucsf** [comment]
Hey @tiagobrc --- Hmmm.... that's pretty interesting. I'm not exactly sure why that is, but my hunch is that it has something to do with a general convergence in transcriptional state between distinct cell types undergoing mitosis.
