### ISSUE TITLE
High pK value, reported doublets don't look right

### ISSUE THREAD

**Issue by FWeilenmann** [chris-mcginnis-ucsf/DoubletFinder#130]
Hi,

I am currently trying to use DoubletFinder to identify and remove doublets from rodent scRNA data.
I have two conditions that I'm processing separately but both result in high pK values when I run paramSweep_v3 and the plots of the expression levels of the doublets and singlets don't resemble images I found online. (ex. https://nbisweden.github.io/workshop-scRNAseq/labs/compiled/seurat/seurat_01_qc.html#Predict_doublets)

I've only added the code and plots of one of the two conditions since they're fairly similar.

Filtering
seurat_object <- subset(seurat_object, subset = nFeature_RNA > 200 & nFeature_RNA < 5000 & nCount_RNA > 300 & nCount_RNA < 15000 & percent.mt < 10)

SCTransform
seurat_object <- SCTransform(seurat_object, vars.to.regress = "percent.mt", variable.features.n = 10000)

PCA
seurat_object <- RunPCA(object = seurat_object)

Number op PCs were calculated with:
    pct <- seurat_object[["pca"]]@stdev / sum(seurat_object[["pca"]]@stdev) * 100
    # Determine percent of variation associated with each PC
    # calculate cumulative percents for each PC   
    cumu <- cumsum(pct)   
    # Determine which PC exhibits cumulative percent greater than 90% and % variation associated with the PC as less than 5
    co1 <- which(cumu > 90 & pct < 5)[1]
    co2 <- sort(which((pct[1:length(pct) - 1] - pct[2:length(pct)]) > 0.1), decreasing = T)[1] + 1   
    pcs <- min(co1, co2)
    rm(co1,co2,pct,cumu)
    pcs

DoubletFinder
sweep.res <- paramSweep_v3(seurat_object, PCs = 1:pcs, sct = T)
sweep.stats <- summarizeSweep(sweep.res, GT = FALSE) 
bcmvn <- find.pK(sweep.stats)

bcmvn[bcmvn$BCmetric == max(bcmvn$BCmetric),]
   _ParamID     pK        MeanBC        VarBC                BCmetric
   25               0.24     0.8028244     0.0001002408   8008.961_

![image](https://user-images.githubusercontent.com/98521211/151334726-1e51db91-017a-4eb0-a1f7-c21b00c79a78.png)

(I'm not sure why it always prints blank axes but I double checked the peak and it belongs to pK = 0.24)

![DF_seurat_object_expression](https://user-images.githubusercontent.com/98521211/151334098-6204970b-5f65-4119-80de-d488bd50b694.png)

I was expecting the doublets to have higher nFeatures and/or nCounts. Did I make a mistake somewhere? The cells belong to a single brain region so maybe they aren't diverse enough to generate reliable heterotypic doublets?

**Comment by chris-mcginnis-ucsf** [comment]
hey @FWeilenmann -- I usually do not do a high nFeature/nCount threshold because that is going to exclude the presumed doublets. Perhaps DF is getting thrown off by this? Also, have you looked at the lower BCmvn pK peak?

**Comment by FWeilenmann** [comment]
Hi @chris-mcginnis-ucsf,

Thanks for the quick reply!

I've check expression levels of doublets and singlets at pK 0.005; 0.18; and 0.24. 
The ones at 0.005 are most similar to my expectations (high nFeatures and nCounts for doublets)

pK0.005
![file_show](https://user-images.githubusercontent.com/98521211/151944022-27589c3e-8db4-4cd4-b0cb-47f7d1b2b1de.png)

pk 0.18
![file_show](https://user-images.githubusercontent.com/98521211/151944069-2d4d4a45-b20d-4f82-a207-1a9999c2108b.png)

pK 0.24
![file_show](https://user-images.githubusercontent.com/98521211/151944078-378442a2-93f7-4e25-9d5f-877853dac7fa.png)

I'll run the code again without the upper thresholds and see whether that helps with the prediction.
