### ISSUE TITLE
SCT v2 release

### ISSUE THREAD

**Issue by rbutleriii** [chris-mcginnis-ucsf/DoubletFinder#131]
Hi Chris,

Seurat just released SCTransform v2 with some improvements. Would it be possible to add that as an option in `paramSweep`?

Thanks,
Rob

**Comment by chris-mcginnis-ucsf** [comment]
Hi @rbutleriii -- will incorporate this soon! Thanks for bringing it to my attention

**Comment by saeedfc** [comment]
Hi,

Being compatible with Seurat v4 in general may also requires to specify the 'method' part in sctransform to use 'glmgampoi' over 'vst'.
For the time being I am just editing the function to include the argument for sctransform function > method = 'glGampoi'.

**Comment by ThanosPAS** [comment]
Personally, this is how I made it work:

cells <- SCTransform(cells, assay = "RNA", new.assay.name = "SCT", method = "glmGamPoi", vars.to.regress = "percent.mt",verbose = FALSE, vst.flavor = "v2")

**Comment by rbutleriii** [comment]
By default glmgampoi is called in SCTv2:
https://github.com/satijalab/seurat/issues/5585

**Comment by chris-mcginnis-ucsf** [comment]
On it.
