### ISSUE TITLE
Reopening #115?

### ISSUE THREAD

**Issue by ThanosPAS** [chris-mcginnis-ucsf/DoubletFinder#134]
The error seems to emerge even without an integrated Seurat object within the data structure. More info on the new bug as a comment at: [#115](https://github.com/chris-mcginnis-ucsf/DoubletFinder/issues/115)

**Comment by ccy2018** [comment]
Hi @ThanosPAS 
It seems you used SCTransform during original Seurat object pre-processing.
According to "paramSweep_v3", "sct" refers to "Logical representing whether SCTransform was used during original Seurat object pre-processing (default = FALSE)."
So I guess maybe "sct=T" will help?

**Comment by jgarces02** [comment]
Hi. I think the error is not caused by `SCTransform`... I've the same problem and I didn't perform any integration or transformation.
```
aux_gex <- Read10X("sample_filtered_feature_bc_matrix")
aux_seurat <- CreateSeuratObject(counts = aux_gex, min.cells = 0)
aux_seurat[["MT_pct"]] <- PercentageFeatureSet(aux_seurat, pattern = "^MT-")

aux_seurat <- subset(aux_seurat, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & MT_pct < 10) %>% 
  NormalizeData() %>% FindVariableFeatures() %>% ScaleData() %>% RunPCA()

nExp <- round(ncol(aux) * 0.07)  #expect ~7% doublets
aux <- doubletFinder_v3(aux, pN = 0.25, pK = 0.09, nExp = nExp, PCs = 1:10)

[1] "Creating 1163 artificial doublets..."
[1] "Creating Seurat object..."
[1] "Normalizing Seurat object..."
Error in NormalizeData.default(object = GetAssayData(object = object,  :
  trying to get slot "params" from an object of a basic class ("NULL") with no slots
```
(I'm working with Seurat version 3.1.0).

Thanks

**Comment by Lopo358** [comment]
I am getting the same error message on unintegrated data

**Comment by iichelhadi** [comment]
Same issue on unintegrated data. it seems sctransform and doubletfinder are not compatible since doubletfinder can't find the correct slot

**Comment by purisuto** [comment]
I got the same issue with a Seurat object that has HTO and ADT assay slots.  Any luck making it work regardless?

**Comment by iichelhadi** [comment]
no I haven't I just ran doublet finder on log normalised data then took the metadata with the doublet info and added it to the non processed seurat obj and then ran "sct"

**Comment by mtekman** [comment]
Chiming in to say I'm experiencing this too on both integrated and unintegrated data

**Comment by chris-mcginnis-ucsf** [comment]
Hi all -- I would generally suggest using DF 'as advertised', it is tricky to anticipate all of the different types of inputs folks will be working with, so before using DF I would just start with a 'fresh' (QC'd) seurat object and follow the tutorial

**Comment by jianwu1** [comment]
> it is tricky to anticipate all of the different types of inputs folks will be working with

It might be useful to change the source code from `seu@assays$RNA@counts` to `LayerData(seu, layer = "counts")` so that it gives the counts matrix for whatever layer that is active, whether SCT or RNA.
