### ISSUE TITLE
Aggregate data matrices after DoubletFinder run

### ISSUE THREAD

**Issue by Rahul1711arora** [chris-mcginnis-ucsf/DoubletFinder#138]
Hi, 

I have been reading on how to use DoubletFinder and it seems that it makes sense to not use it on aggregated data. 
But my question is that if the aggregated data contains only either the wild types or the mutants, then is it okay to run Doublet Finder on each of the aggregated matrices separately? 
I anyway do not intend to merge them at this point but perhaps, it should be okay to merge them after removing the doublets, is that correct? 

Thanks in advance for your help. 

Best,
Rahul

**Comment by chris-mcginnis-ucsf** [comment]
Hi @Rahul1711arora ,

If they were run on different 10x lanes I would not merge. If the mutants have a transcriptional effect (which I would imagine they do, hence the experiment) then running on the merged data if the data was generated using different 10x lanes (i.e., WT and mutant split) will cause DF to 'find' doublets that do not exist (e.g., mutant-WT doublets), hence skewing the results.

Chris
