### ISSUE TITLE
DoubletFinder pK Identification error : Error in match.arg(arg = slot) : 'arg' must be NULL or a character vector

### ISSUE THREAD

**Issue by matteozoia4** [chris-mcginnis-ucsf/DoubletFinder#139]
Dear Chris,

everything runs smoothly till the step : ## pK Identification (no ground-truth) 
`sweep.res.list_heart <- paramSweep_v3(myseuratobject, PCs = 1:10, sct = FALSE)`

I got this error : 
`Error in match.arg(arg = slot) : 'arg' must be NULL or a character vector`

What could this be related to? 

Best and thank you in advance!

**Comment by LiorYeSof** [comment]
Have you performed SCTransform? if so change sct = T and it should work

**Comment by chris-mcginnis-ucsf** [comment]
@matteozoia4 ,

See @LiorYeSof 's comment -- did that work? Email me if not.

Chris

**Comment by Pedramto89** [comment]
Hi
I have the same issue. I used SCT and set it to TRUE but did not change the result. I still get the error. 
This is the pipeline I follow:
`obj <- SCTransform(obj, assay = "Spatial", verbose = FALSE)
obj <- FindVariableFeatures(obj, assay="SCT")
obj <- ScaleData(obj)
obj <- RunPCA(obj, assay = "SCT", verbose = FALSE)
ElbowPlot(obj)
obj <- FindNeighbors(obj, reduction = "pca", dims = 1:20)
obj <- FindClusters(obj, verbose = FALSE)
obj <- RunUMAP(obj, reduction = "pca", dims = 1:20)`

And this is the error:
`Error in paramSweep_v3(obj, PCs = 1:20, sct = F) : 
  trying to get slot "counts" from an object of a basic class ("NULL") with no slots`
