### ISSUE TITLE
Is RunUMAP critical for calculating doublets?

### ISSUE THREAD

**Issue by levinhein** [chris-mcginnis-ucsf/DoubletFinder#141]
Hi. Thank you for you  package. One datasets apparently has had the RunUMAP step errored, but the next steps/codes still functioned well and the doublets were still calculated. I wonder if I should worry about it or I must correct it? 

![image](https://user-images.githubusercontent.com/68268222/181513834-cd70658c-2c69-4b29-8b2e-5b84a0658fba.png)

**Comment by chris-mcginnis-ucsf** [comment]
Hi @levinhein ,

Run UMAP isn't necessary, although those UMAPs look very weird to me.... I wouldn't read too much into these data.

Chris
