### ISSUE TITLE
paramSweep_v3_error

### ISSUE THREAD

**Issue by Arice127** [chris-mcginnis-ucsf/DoubletFinder#143]
Hi, @Developer,
Thank you for developing this excellent tool.
I have an error when I run paramsweep_v3 for only one seurat object (I had no problem when running other seurat objects).

DoubletFinder: Error in h(simpleError(msg, call)): Error in evaluating the'x' parameter when selecting the method for the't' function: Missing values ​​cannot be used where TRUE/FALSE values ​​are required Calls: RunDF ... resolve.list -> signalConditionsASAP -> signalConditions

The code is below:

library(Seurat)
library(dplyr) 
library(patchwork)
library(ggplot2)
library(sctransform)
library(DoubletFinder)
set.seed(1234)

rawdata12 <- Read10X(data.dir = "~/count/sample_feature_bc_matrix")
data12 <- CreateSeuratObject(counts = rawdata12[["Gene Expression"]], project = "X", min.cells = 3, min.features = 100)
data12[["percent.mt"]] <- PercentageFeatureSet(data12, pattern = "^MT-")
data12 <- subset(data12, subset=nFeature_RNA > 500 & percent.mt < 5)
data12 <- SCTransform(data12)
data12 <- RunPCA(data12)
data12 <- FindNeighbors(data12, reduction = "pca", dims = 1:10)
data12 <- FindClusters(data12, resolution = 0.05

#run umap
data12 <- RunUMAP(data12, reduction = "pca", dims = 1:10, return.only.var.genes = FALSE)	

DefaultAssay(data12) <- "SCT"

sweep.res.list_data12 <- paramSweep_v3(data12, PCs = 1:10, sct = TRUE) 

There happens an error like this.

#Try help(fields) to get started.
##[1] "Creating artificial doublets for pN = 5%"
##[1] "Creating Seurat object..."
##[1] "Running SCTransform..."
#Calculating cell attributes from input UMI matrix: log_umi
#Variance stabilizing transformation of count matrix of size 17204 by 1646
#Model formula is y ~ log_umi
#Get Negative Binomial regression parameters per gene
#Using 2000 genes, 1646 cells
#  |======================================================================| 100%
#There are 1 estimated thetas smaller than 1e-07 - will be set to 1e-07
#Found 96 outliers - those will be ignored in fitting/regularization step

#Second step: Get residuals using fitted parameters for 17204 genes
#  |======================================================================| 100%
#Computing corrected count matrix for 17204 genes
#  |======================================================================| 100%
#Calculating gene attributes
#Wall clock passed: Time difference of 47.90184 secs
#Determine variable features
#Place corrected count matrix in counts slot
#Centering data matrix
#  |======================================================================| 100%
#Set default assay to SCT
##[1] "Running PCA..."
#PC_ 1 
#Positive:  ~
#Negative:  ~
#PC_ 2 
#Positive: ~
#Negative: ~
#PC_ 3 
#Positive:  ~
#Negative:  ~
#PC_ 4 
#Positive:  ~
#Negative:  ~
#PC_ 5 
#Positive:  ~
#Negative: ~
##[1] "Calculating PC distance matrix..."
#[1] "Defining neighborhoods..."
#[1] "Computing pANN across all pK..."
#[1] "pK = 0.01..."
#[1] "pK = 0.02..."
#[1] "pK = 0.03..."
#[1] "pK = 0.04..."
#[1] "pK = 0.05..."
#[1] "pK = 0.06..."
#[1] "pK = 0.07..."
#[1] "pK = 0.08..."
#[1] "pK = 0.09..."
#[1] "pK = 0.1..."
#[1] "pK = 0.11..."
#[1] "pK = 0.12..."
#[1] "pK = 0.13..."
#[1] "pK = 0.14..."
#[1] "pK = 0.15..."
#[1] "pK = 0.16..."
#[1] "pK = 0.17..."
#[1] "pK = 0.18..."
#[1] "pK = 0.19..."
#[1] "pK = 0.2..."
#[1] "pK = 0.21..."
#[1] "pK = 0.22..."
#[1] "pK = 0.23..."
#[1] "pK = 0.24..."
#[1] "pK = 0.25..."
#[1] "pK = 0.26..."
#[1] "pK = 0.27..."
#[1] "pK = 0.28..."
#[1] "pK = 0.29..."
#[1] "pK = 0.3..."
#[1] "Creating artificial doublets for pN = 10%"
#[1] "Creating Seurat object..."
#[1] "Running SCTransform..."
#Calculating cell attributes from input UMI matrix: log_umi
#Variance stabilizing transformation of count matrix of size 17442 by 1738
#Model formula is y ~ log_umi
#Get Negative Binomial regression parameters per gene
#Using 2000 genes, 1738 cells
#  |====================================================                  |  75% 
Error in h(simpleError(msg, call)): Error in evaluating the'x' parameter when selecting the method for the't' function: Missing values ​​cannot be used where TRUE/FALSE values ​​are required Calls: RunDF ... resolve.list -> signalConditionsASAP -> signalConditions

How can I fix for this error?
I tried to change the method of SCTransform to "glmGamPoi" in paramSweep_v3, but it didn't work.

Thank you,
Risa

**Comment by chris-mcginnis-ucsf** [comment]
Hi @Arice127 ,

Nothing in the code you show above looks off to me... How does he data look when you play around with it in Seurat? Have you figured this out? Email me if not...

Chris

**Comment by Arice127** [comment]
Hi @[chris-mcginnis-ucsf](https://github.com/chris-mcginnis-ucsf), Thank you for your reply.

I haven't solved it yet. The seurat object (data12) can be processed and described as UMAP normally in Seurat.

If you could give me some advice, I would appreciate it.

Sincerely,
Risa
