### ISSUE TITLE
paramSweep_v3 reproducibility

### ISSUE THREAD

**Issue by joyduck** [chris-mcginnis-ucsf/DoubletFinder#144]
just noticed that the paramSweep_v3() function is not reproducible, it generates different results every time I run it, as a consequence, the final cell clusters vary as well, tried to set seed but it did not help. I'm wondering if there is a way to make the result more reproducible.
Thanks.

**Comment by wudustan** [comment]
I have had this issue as well. Sometime the parameters can be quite different.

**Comment by joyduck** [comment]
I'm not the author but hope this is helpful for you.
I went through the package and found that there are multiple functions in the package that used the R basic sample function, but did not set seed for these sample functions, that is why everything is changing every time you used it, it will not work by just set ting seed before using the package as well,  because there are multiple of these occasions, the seed will only work for the first time.  however, if you have less than 5000 cells, this might be not an issue for you. 

The fix is to make your own functions for all these sample-containing functions by adding set.seed before every sample function, there were additional functions that need to be fixed beyond this paramSweep_v3(),  I have tested, and doing this will fix the issue.

**Comment by adRn-s** [comment]
Reproducibility is there in essence, since the results are not changing dramatically (e.g. they are compatible between runs, and you can derive the same conclusions).

PS. I always have `` set.seed()`  as first line in my code/ R session. This may be affecting my perception.

**Comment by joyduck** [comment]
I don't think we are talking about the same thing here.

> Reproducibility is there in essence, since the results are not changing dramatically (e.g. they are compatible between runs, and you can derive the same conclusions).
> 
> PS. I always have `` set.seed()` as first line in my code/ R session. This may be affecting my perception.

**Comment by smallfishcui** [comment]
> I don't think we are talking about the same thing here.
> 
> > Reproducibility is there in essence, since the results are not changing dramatically (e.g. they are compatible between runs, and you can derive the same conclusions).
> > PS. I always have `` set.seed()` as first line in my code/ R session. This may be affecting my perception.

Would you mind sharing your code? I am having the same issue, and it seems the pK of the same dataset varies from 4%-20%, that's too instable for my dataset. And how do you know which seed produces the best result?

Thanks!
Cui
