### ISSUE TITLE
The detected doublet cells are always the top cells in the dataset

### ISSUE THREAD

**Issue by rauldiul** [chris-mcginnis-ucsf/DoubletFinder#147]
Hi Chris,

First of all thanks for your work.

I've set up DoubletFinder, and I'm getting back a very strange result: my cells labeled as doublets are always the first cells of my dataset. Because my dataset is not pre-sorted by anything, and I don't see that DoubletFinder changes the order of the cells, I find this very hard to understand. What I mean is, when I do a `head(dataset$DF.classifications)`, the result is always `doublet, doublet, doublet....` and then all the singlet cells. But the cells are in the original order as I input them, so it is very strange that only the first cells would always happen to be doublets.

I leave you below the code that I'm using on DoubletFinder v2.0.3.

Thanks for your help and best regards

Here's the code that I'm using:

```
#######################################
# Preprocess

# Normalize and reduce dims to produce clustering
x <- SCTransform(x) # This already selects 3000k variable features
x <- RunPCA(x, assay = "SCT", npcs = 50) # This uses variable features by default
x <- RunUMAP(x, dims = 1:20)

# Cluster data
x <- FindNeighbors(object = x, dims = 1:20)              
x <- FindClusters(object = x, resolution = 0.8) # Default

#######################################
# Define doublets

# Find parameters: we have no ground-truth. Perform a parameter sweep to find optimal pK:
sweep.res <- paramSweep_v3(x, PCs = 1:20, sct = TRUE)
sweep.stats <- summarizeSweep(sweep.res, GT = FALSE)
bcmvn <- find.pK(sweep.stats)

# Optimal pK is the max of the bomodality coefficent (BCmvn) distribution 
optimal.pk <- as.numeric(bcmvn$pK[which.max(bcmvn$BCmetric)])

# Estimate Homotypic Doublet Proportion (doublets with similar transcriptomes)
annotations <- x@meta.data$seurat_clusters
homotypic.prop <- modelHomotypic(annotations)
nExp_poi <- round(0.04*nrow(x@meta.data))  # Assuming 4% doublet formation rate
nExp_poi.adj <- round(nExp_poi*(1-homotypic.prop))

# Run doublet finder
x <- doubletFinder_v3(x, PCs = 1:20,
                      pN = 0.25, # leave as default
                      pK = [optimal.pk](http://optimal.pk/), # using empirical optimal pK
                      nExp = nExp_poi.adj, # using adjusted nExp
                      reuse.pANN = FALSE,
                      sct = TRUE)

# Rename column: The classifications are in: x$DF.classifications_0.25_4_172
colnames(x@meta.data)[grepl("DF.classifications",colnames(x@meta.data))] <- "DoubletFinder"

head(x$DoubletFinder)
```

**Comment by chris-mcginnis-ucsf** [comment]
hey @rauldiul ,

I honestly have no idea what might be happening here lol...

Do the doublet classification results make sense biologically? If so, maybe you reordered the metadata slot at some point? 

Chris

**Comment by isaiahwtaylor** [comment]
I recall having a similar seeming problem (not as extreme, but the called doublets were enriched in the early barcodes of the object). I think this may have fixed it (don't ask me why!) 

pK = as.numeric(as.character(bcmvn[max(bcmvn$BCmetric)==bcmvn$BCmetric,2][1]))

To check, you could see what the value of optimal.pk is. In my situation I was coding something wrong and it was always 0.
