### ISSUE TITLE
doubletFinder code

### ISSUE THREAD

**Issue by jiangzh-coder** [chris-mcginnis-ucsf/DoubletFinder#148]
Hi, everyone!

I want to ask a question about doubletFinder application for mutiple samples. 
I inserted doubletFinder code into my code which was derived from following website:
https://nbisweden.github.io/workshop-scRNAseq/labs/compiled/seurat/seurat_01_qc.html

dataL <- SplitObject(seu1, split.by = "orig.ident")

for (idx in 1:length(dataL)) {
  ## preprocessing
  data <- NormalizeData(dataL[[idx]],normalization.method="LogNormalize", 
                        scale.factor=10000)
  data <- FindVariableFeatures(data, selection.method="vst", nfeatures=2000)
  data <- ScaleData(data, verbose = FALSE)
  data <- RunPCA(data, verbose = FALSE)
  data <- RunUMAP(data, reduction = "pca", dims = 1:30)
  
  sweep.res.list <- paramSweep_v3(data, PCs = 1:30, sct = FALSE)
  sweep.stats <- summarizeSweep(sweep.res.list, GT = FALSE)
  bcmvn <- find.pK(sweep.stats)
  mpK<-as.numeric(as.vector(bcmvn$pK[which.max(bcmvn$BCmetric)]))
  
  ## Homotypic Doublet Proportion Estimate -------------------------------------------------------------------------------------
  annotations <- data@meta.data$ClusteringResults
  homotypic.prop <- modelHomotypic(annotations)   ## ex: annotations <- sample14@meta.data$ClusteringResults
  DoubletRate = ncol(data)*8*1e-6
  nExp_poi <- round(DoubletRate*nrow(data@meta.data))  ## Assuming 7.5% doublet formation rate - tailor for your dataset
  nExp_poi.adj <- round(nExp_poi*(1-homotypic.prop))
  
  ## Run DoubletFinder with varying classification stringencies ----------------------------------------------------------------
  data <- doubletFinder_v3(data, PCs = 1:30, pN = 0.25, pK = mpK, 
                           nExp = nExp_poi, reuse.pANN = FALSE, sct = FALSE)
  data <- doubletFinder_v3(data, PCs = 1:30, pN = 0.25, pK = mpK, 
                             nExp = nExp_poi.adj, reuse.pANN = FALSE, sct = F)
  ## save results
  dataL[[idx]]$doubFind_res = data@meta.data %>% select(contains('DF.classifications'))
  dataL[[idx]]$doubFind_score = data@meta.data %>% select(contains('pANN'))
}

However, i got following results:
table(scRNA_harmony@meta.data$sbt_is_doublet.orig) -------##This dataset has been analyzed by Scrublet software, the results 
                                                                                                    ##stored in meta.data! 
#FALSE
#46663
table(scRNA_harmony@meta.data$manually_is_doublet.orig) -------##by hands
#FALSE
#46663
table(scRNA_harmony@meta.data$doubFind_res) --------##by doubletFinder
#Doublet Singlet
#2316   44347

Does doubletFinder detect more untrue Doublets? 
Or, my code is wrong? 

best wishes
Jiang

**Comment by chris-mcginnis-ucsf** [comment]
Hi @jiangzh-coder ,

Thanks for providing code, but I'm having trouble following. The total number of doublets is a user-defined parameter, so that could explain why scrublet vs DF are giving different results.

Chris
