### ISSUE TITLE
Missing dependencies in `DESCRIPTION`

### ISSUE THREAD

**Issue by dtelad11** [chris-mcginnis-ucsf/DoubletFinder#15]
When running package functions R raised an error that packages `fields` and `modes` are missing. You can add them as dependencies in `DESCRIPTION` to make sure users install them before running the package.

**Comment by chris-mcginnis-ucsf** [comment]
Thanks! Fixed, closing issue now.

**Comment by NathanSkene** [comment]
I'm still getting this issue. There's currently no reference to fields in NAMESPACE or DESCRIPTION. Run devtools::document() and then commit changes?

**Comment by vitkl** [comment]
I have the same problem.

**Comment by chris-mcginnis-ucsf** [comment]
Should be fixed now -- added Imports: fields, modes, Seurat, KernSmooth, ROCR to the DESCRIPTION
