### ISSUE TITLE
Almost all cells as doublets

### ISSUE THREAD

**Issue by MartaSanchezCarbonell** [chris-mcginnis-ucsf/DoubletFinder#150]
Dear Chris,

Congratulations for the great work with DoubletFinder. I would like to share a problem that I am having. I am working with my datasets, involving several developmental timepoints of mice brain. I have recognised that, in general, all the cells that look like transition states between cell identities or have stem cell traits are labelled as doublets. Specifically, the dataset with cells form P0 animals (cells collected right after birth) shows an extreme situation, 85% of my cells are labelled as doublets. I guessed that the algorithm considers almost all cells as doublets because during development almost all cells are in transition state or in stem cell state. 

Could it be that this is affecting the algorithm? Has anyone encountered this situation as well? Is there a way to adjust doublet finder for transition and stem cell states?

Best regards,

Marta

**Comment by chris-mcginnis-ucsf** [comment]
Hi @MartaSanchezCarbonell ,

The number of cells that are called as doublets is a user-defined parameter (nExp in doubletFinder_v3) so if 85% of cells are labelled as doublets that means you are setting nExp to 85% of the dataset size. Have you tried setting nExp according to the poisson doublet rate as defined in the 10x protocol? 

Also, we tested DF on data with intermediate cell types and the algo is able to distinguish -- wondering if this holds true for your data.

Chris

**Comment by MartaSanchezCarbonell** [comment]
Dear @chris-mcginnis-ucsf ,

Thank you very much for your answer and sorry for my late response. You were right, the % of doublets was wrongly supplied. However, even if we fixed this problem, we still find some cell populations with higher % of doublets compared with others. We tend to find more doublets in stem cell populations or in microglia, endothelial cells and oligodendrocytes (percentages ranging from 20% to 70% or even some clusters completely labelled as doublets). On the other hand, we find almost 0% of doublets in clusters that belong to neurons.

Did you encounter any person with the same situation?

Best regards,

Marta
