### ISSUE TITLE
paramsweep error in for loop

### ISSUE THREAD

**Issue by jessicaliu70** [chris-mcginnis-ucsf/DoubletFinder#151]
I tried to run paramsweep on a list of seurat objects through for loop.

pk.list<-list()

for (n in 1:10) {
i<-seurat_obj.list[[n]]

sweep.res <- paramSweep_v3(i) 
sweep.stats <-summarizeSweep(sweep.res, GT = FALSE) 
bcmvn <- find.pK(sweep.stats)

pK=as.numeric(as.character(bcmvn$pK))
BCmetric=bcmvn$BCmetric
pK_choose = pK[which(BCmetric %in% max(BCmetric))]
pk.list<-append(pk.list,pK_choose)
}

I always got this error: 
Error in plot.new() : 
  could not open file '.../1/48F12D3/c3rne7sta_t/_rs_chunk_plot_001.png'

It doesn't have this error while run individually. What's wrong?

**Comment by chris-mcginnis-ucsf** [comment]
Hi @jessicaliu70 ,

I think it's just something with the internal R plotting function not being able to print to global env from the loop. Hope running it one at a time isn't too arduous.

Chris
