### ISSUE TITLE
Can I use the merged Seurat object for doublets detection?

### ISSUE THREAD

**Issue by bio-lilin** [chris-mcginnis-ucsf/DoubletFinder#153]
Hi Chris:
I am confused about whether the merged Seurat object can be used directly to compute doublets. In my opinion, since the determination of the parameter nExp ~ is related to cell loading densities into the 10X/Drop-Seq device, it is appropriate to use the pre-merged Seurat object to compute doublets separately. Looking forward to your reply!

**Comment by cgoneill** [comment]
In the best practices heading on readme.md it says you shouldn't use DoubletFinder on merged doublets, as it will create artificial doublets from multiple samples that will skew results. The only exception to this is if the Seurat objects used to generate the merged object from were all technical replicates.

**Comment by chris-mcginnis-ucsf** [comment]
@cgoneill is correct -- thanks.
