### ISSUE TITLE
Problem about PCA

### ISSUE THREAD

**Issue by sanderslhc** [chris-mcginnis-ucsf/DoubletFinder#154]
Hi,

I'm using the Doubletfinder to filter the doublets in my research. In this step, I used all genes to perform PCA and set the PCs as 1:10 because I want to preserve more information of each cell and this PCs range won't lead to many noises. Do you think this is reasonable? Or I must select the HUG? Do they will have significant differences?

Best
Houcheng

**Comment by chris-mcginnis-ucsf** [comment]
Hi @sanderslhc I would suggest looking into normal practices for PCA in Seurat.
