### ISSUE TITLE
Problem with number of artificial doublets

### ISSUE THREAD

**Issue by chopwoods** [chris-mcginnis-ucsf/DoubletFinder#155]
Dear Chris,
I have problem when i run my command like below:
`nExp <- round(nrow(MLB018.sub@meta.data)*0.04)  # expect 4% doublets
MLB018.sub <- doubletFinder_v3(MLB018.sub, pN = 0.25, pK = 0.01, nExp=1824, PCs = 1:10, reuse.pANN = FALSE, sct=FALSE)`
Since the nExp is 1824 in the environment, I tried nExp=nExp or nExp=1824 directly, However, it keep says that  "Creating 15200 artificial doublets...". which is much more than 1824.
Would you know what's wrong with it?

**Comment by ramin-ali-marandi-ghoddousi** [comment]
I believe that the number of "artificial doublets" is determined by your pN value, not by the nExp.  The program compares your cells to these 15200 artificial doublets to determine which 1824 cells in your dataset are most likely doublets.

**Comment by chris-mcginnis-ucsf** [comment]
@ramin-ali-marandi-ghoddousi is correct. Closing this issue.
