### ISSUE TITLE
Higher mean UMIs for Singlets in one sample

### ISSUE THREAD

**Issue by ramin-ali-marandi-ghoddousi** [chris-mcginnis-ucsf/DoubletFinder#157]
Hi Chris,  

Thank you for the amazing tool!  I'm having a possible issue and wanted to get your opinion.  I run DoubletFinder (paramSweep_v3 to determine optimal PK and homotypic adjustment to get adjusted nExp) on 5 of my samples separately and generate nCount_RNA violin plots to check the results.  For most of my samples the median UMI count for my doublets is equal to or higher than the UMI counts for singlets, but one of my samples this is reversed with a large effect size in the opposite direction (see below).  Any idea what could be going on?

![image](https://user-images.githubusercontent.com/64667688/228084356-f5232993-df2e-49ad-9f6d-3ef37882d29f.png)

Thanks!  
Ramin

**Comment by chris-mcginnis-ucsf** [comment]
Hi @ramin-ali-marandi-ghoddousi -- my guess is that you have low-quality cells present in the last sample that are being called as doublets and dragging the mean down. What is the pMito distribution for doublets in that final case?

**Comment by chris-mcginnis-ucsf** [comment]
Closing this unless you want it reopened
