### ISSUE TITLE
Issue with name attribute and vector?

### ISSUE THREAD

**Issue by pdimitron** [chris-mcginnis-ucsf/DoubletFinder#159]
Hello,

I've been scouring the internet for a solution to this problem, but could not find a similar problem. I'm trying to write a function that loops a list of seurat objects through DoubletFinder. I found that someone had an example, but when I made some edits to it, I ran into the following error:

Error in names(sweep.res.list) <- name.vec :
  'names' attribute [192] must be the same length as the vector [6]
In addition: Warning message:
In mclapply(as.list(1:length(pN)), FUN = parallel_paramSweep_v3,  :
  all scheduled cores encountered errors in user code

This occurred after DoubletFinder ran multiple PCAs and since this is my first experience with doubletFinder I'm not sure where the issue is arising. Any help or suggestions would be appreciated.

Thanks!

**Comment by miko-798** [comment]
I have the exact same issue! 

> ## pK Identification (no ground-truth)
> sweep.res.od <- paramSweep_v3(od.clustered, PCs = 1:30, num.cores = 8) 
Error in names(sweep.res.list) <- name.vec : 
  'names' attribute [192] must be the same length as the vector [6]

**Comment by chris-mcginnis-ucsf** [comment]
Hi @miko-798 and @pdimitron -- I'm not sure what's going on here. Tough to debug without your code. Closing now but will reopen if you respond.

**Comment by ishwarvh** [comment]
@pdimitron and @miko-798 Were you folks able to resolve this issue?

@chris-mcginnis-ucsf This error seems to be appear only when trying to run paramSweep_v3 on multiple cores.

**Comment by cmiciano** [comment]
@chris-mcginnis-ucsf  I'm seeing the same thing as @ishwarvh, has there been a fix when running on multiple cores for seuratv5 objects? (also referenced #159 and #180)

```
Error in names(sweep.res.list) <- name.vec : 
  'names' attribute [192] must be the same length as the vector [162]
Calls: suppressMessages -> withCallingHandlers -> paramSweep
In addition: Warning message:
In mclapply(as.list(1:length(pN)), FUN = parallel_paramSweep, n.real.cells,  :
  scheduled core 1 did not deliver a result, all values of the job will be affected
Execution halted
```

**Comment by cetinsz** [comment]
I am also having the same error with seuratv5 object.

**Comment by JaneChik** [comment]
I am using DoubletFinder v 2.0.6 for Seurat v5 objects and still have the same issue. For some samples the parallel computing is ok and for others it results in an error:

```
Error in names(sweep.res.list) <- name.vec : 
  'names' attribute [186] must be the same length as the vector [156]
In addition: Warning message:
In mclapply(as.list(1:length(pN)), FUN = parallel_paramSweep, n.real.cells,  :
  scheduled core 6 encountered error in user code, all values of the job will be affected
```

Running without parallelization resulted in an error on the last iteration:

```
Error in getGlobalsAndPackages(expr, envir = envir, globals = globals) : 
  The total size of the 19 globals exported for future expression (‘FUN()’) is 514.74 MiB. This exceeds the maximum allowed size 500.00 MiB per by R option "future.globals.maxSize". This limit is set to protect against transfering too large objects to parallel workers by mistake, which may not be intended and could be costly. See help("future.globals.maxSize", package = "future") for further explainations and how to adjust or remove this threshold The three largest globals are ‘FUN’ (494.99 MiB of class ‘function’), ‘umi_bin’ (19.19 MiB of class ‘numeric’) and ‘data_step1’ (263.98 KiB of class ‘list’)
```

Setting `options(future.globals.maxSize = 600*1024^2)` resolved the issue. 

R version 4.5.1
