### ISSUE TITLE
Run method without Seurat

### ISSUE THREAD

**Issue by zji90** [chris-mcginnis-ucsf/DoubletFinder#16]
Is it possible to run the method without Seurat? For example starting from a raw count or normalized gene expression matrix?

**Comment by chris-mcginnis-ucsf** [comment]
Unfortunately no, we wrote the software to specifically interface with Seurat. You should check out scrublet -- it is conceptually analogous and works on any data type (https://github.com/AllonKleinLab/scrublet)
