### ISSUE TITLE
RunPCA Error: irlba(A = t(x = object), nv = npcs, ...) :    BLAS/LAPACK routine 'DLASCL' gave error code -4

### ISSUE THREAD

**Issue by levinhein** [chris-mcginnis-ucsf/DoubletFinder#162]
Dear DoubletFinder team, 

Hello, good day! May I ask if you have encountered this error when running DoubletFinder and do you have any suggestions on how to resolve this please? Thank you!

![image](https://github.com/chris-mcginnis-ucsf/DoubletFinder/assets/68268222/3a9b4248-7941-44f0-9339-ce8d2ae93247)

```
> A <- RunPCA(A)
Error in irlba(A = t(x = object), nv = npcs, ...) : 
  BLAS/LAPACK routine 'DLASCL' gave error code -4
```

**Comment by chris-mcginnis-ucsf** [comment]
Hi @levinhein I've never seen this error before, sorry. Closing unless you want reopened.
