### ISSUE TITLE
Problem with using num.cores parameter

### ISSUE THREAD

**Issue by dariotommasini** [chris-mcginnis-ucsf/DoubletFinder#163]
Hi DoubletFinder team, 

I'm having trouble using the num.cores parameter in the paramSweep_v3 function on a cluster. If I use a value greater than 1, the function gets stuck endlessly. I think this has to do with line 32, "cl <- makeCluster(num.cores)". I might be wrong, but my understanding is that makeCluster is for socketing, whereas mclapply uses forking. On my Mac, the function works, perhaps because the makeCluster call is ignored, whereas on a cluster the function fails likely because it actually generates the socket cluster without giving it further instructions. 

I would love to get DoubletFinder parallelization working on the cluster, as I plan to use it on several large datasets. Any help on this would be greatly appreciated!

**Comment by chris-mcginnis-ucsf** [comment]
Hey @dariotommasini and @mimisikai -- to be honest this is a bit above my level of expertise and I don't have the bandwidth to look into this. Good luck. Closing unless you would like reopened.
