### ISSUE TITLE
parallel_paramSweep_v3 error

### ISSUE THREAD

**Issue by BenxiaHu** [chris-mcginnis-ucsf/DoubletFinder#168]
Hello,
   When I ran DoubletFinder to remove doublet from scRNA-seq, I got the following error:
Error in names(sweep.res.list) <- name.vec : 
  'names' attribute [192] must be the same length as the vector [6]
Calls: creatObject -> paramSweep_v3
In addition: Warning message:
In mclapply(as.list(1:length(pN)), FUN = parallel_paramSweep_v3,  :
  all scheduled cores encountered errors in user code
Execution halted

**Comment by chris-mcginnis-ucsf** [comment]
I just fixed it -- should work with Seurat V5 now.

Chris
