### ISSUE TITLE
paramSweep question

### ISSUE THREAD

**Issue by Starlord3796** [chris-mcginnis-ucsf/DoubletFinder#169]
Hi there!

I have ran the paramsweep function according to the guide of DoubletFinder, and apparently as the pK increases so does the BCmetric exponentially. 

<img width="1046" alt="image" src="https://github.com/chris-mcginnis-ucsf/DoubletFinder/assets/148771442/d21c802a-537b-4df5-ba62-1a50b29ce1ea">

The data has followed the standard pipeline below:

10x CellRanger Filtered matrix count > SeuratObject > filtering according to mt.percentage and nFeatures > Log Normalization > ScaleData > PCA > Clustering > UMAP > DoubletFinder

Does anyone know why the BCmetric seems to skyrocket as you increase the pK? Am I doing something wrong? 

Thank you in advance!

**Comment by chris-mcginnis-ucsf** [comment]
@Starlord3796 Nope this is fine -- I would try using the bottom peak as well as the top peak and compare results.

Chris
