### ISSUE TITLE
DoubletFinder using aligned Seurat object

### ISSUE THREAD

**Issue by 23sd98fg** [chris-mcginnis-ucsf/DoubletFinder#17]
Hi, DoubletFinder seems to be a very nice tool that I would like to apply on my own aligned Seurat dataset. Here, the Seurat object is pre-processed slightly different as different commands are used e.g. RunCCA instead of RunPCA etc (see also here: https://satijalab.org/seurat/immune_alignment.html). 
Already with the first command in pK Identification I get an error:

[1] "Running PCA..."
Error in irlba(A = t(x = data.use), nv = pcs.compute, ...) : 
  max(nu, nv) must be positive

I assume it is due to differences in the commands. Is it possible to adapt the underlying functions of DoubletFinder so that it can be used for aligned Seurat objects? That would be really great!

**Comment by chris-mcginnis-ucsf** [comment]
Hello!

Thanks for bringing this to my attention. My sense is that CCA-aligned scRNA-seq data should not be analyzed with DoubletFinder but, rather, DoubletFinder should be run on each unaligned dataset individually. 

Assuming that your experimental design was something similar to the Seurat vignette (e.g., stimulated and control PBMCs run on distinct 10X lanes), running DoubletFinder on the merged data will cause the generation of artificial doublets that _could not_ exist in your data. For example, DoubletFinder would create artificial doublets derived from stimulated and control B-cells in this context, even though those cells are necessarily absent. Although I have never tested this explicitly, I believe this would totally throw off your results.

Curious to hear what you think about this -- I will hold off on adding the functionality until I've heard your thoughts / thought more deeply about this, myself.

**Comment by 23sd98fg** [comment]
Hi Chris, 

Thank you very much for your quick response. I see, that is of course a valid point. I don't know how much your tool is affected by too many falsely predicted, non-existing doublets. 

There are commands in the Seurat alignment pipeline to distinguish between the control and stimulated datasets, e.g. group.by = "stim" or grouping.var = "stim". I could imagine that this would be a way to compute the potential doublets only within the respective groups that were aligned?
I hope that helps. 

Best, 
Laura

**Comment by chris-mcginnis-ucsf** [comment]
That's a good idea, but one issue that DoubletFinder purposefully utilizes the same pre-processing parameters as were used during the initial workflow (i.e., without artificial doublets). 

All of these parameters -- and most importantly, the number of significant PCs and corresponding embedding -- will require separately processing each sample (unless all of the sample were pooled in a single 10X lane, as you can do with sample multiplexing approaches like Cell Hashing, Click-Tags, MULTI-seq, etc.). For this reason, I will not include code for handling aligned data -- but I will add a note about this in the readme.

Chris
