### ISSUE TITLE
Doubletfinder in Seurat v5

### ISSUE THREAD

**Issue by lisch7** [chris-mcginnis-ucsf/DoubletFinder#171]
Hi,

Doubletfinder is indeed a great tool for identifying doublets. However, the function `paramSweep_v3` is not compatible with the Seurat v5 pipeline.

```
Error in paramSweep_v3(sce, PCs = 1:10, sct = FALSE) : 
  no slot of name "counts" for this object of class "Assay5"
```

Could you help to fix the problem? Thanks.

**Comment by lemon-latte** [comment]
this problem is due to the code in [paramSweep_v3.R](https://github.com/chris-mcginnis-ucsf/DoubletFinder/blob/master/R/paramSweep_v3.R), L24: data <- seu@assays$RNA@counts; however the count data is saved in seu@assays$RNA@layers$data, so the Error happend. You can download all code and modify the code for paramSweep_v3.R 

  if (nrow(seu@meta.data) > 10000) {
    real.cells <- rownames(seu@meta.data)[sample(1:nrow(seu@meta.data), 10000, replace=FALSE)]
    data <- seu[["RNA"]]$counts[ , real.cells]
    n.real.cells <- ncol(data)
  }

  if (nrow(seu@meta.data) <= 10000){
    real.cells <- rownames(seu@meta.data)
    data <- seu[["RNA"]]$counts
    n.real.cells <- ncol(data)
  }

source all code and you can continue to do doublefinder

**Comment by lisch7** [comment]
Thanks for your kind reply!

> this problem is due to the code in [paramSweep_v3.R](https://github.com/chris-mcginnis-ucsf/DoubletFinder/blob/master/R/paramSweep_v3.R), L24: data <- seu@assays$RNA@counts; however the count data is saved in seu@assays$RNA@layers$data, so the Error happend. You can download all code and modify the code for paramSweep_v3.R
> 
> if (nrow([seu@meta.data](mailto:seu@meta.data)) > 10000) { real.cells <- rownames([seu@meta.data](mailto:seu@meta.data))[sample(1:nrow([seu@meta.data](mailto:seu@meta.data)), 10000, replace=FALSE)] data <- seu[["RNA"]]$counts[ , real.cells] n.real.cells <- ncol(data) }
> 
> if (nrow([seu@meta.data](mailto:seu@meta.data)) <= 10000){ real.cells <- rownames([seu@meta.data](mailto:seu@meta.data)) data <- seu[["RNA"]]$counts[ , real.cells] n.real.cells <- ncol(data) }
> 
> Meanwhile, the code doubletFinder_v3 need to be modified: L16 data <- seu@assays$RNA@counts[, real.cells] => data <- seu[["RNA"]]$counts[, real.cells]
> 
> source all code and you can continue to do doublefinder

**Comment by chris-mcginnis-ucsf** [comment]
I just fixed it -- should work with Seurat V5 now.

Chris

**Comment by lchjinguw** [comment]
I just installed Seurat v5, and this doubletFinder still has the issue. Something wrong in my part?

> BM16216.combined <- doubletFinder_V3(BM16216.combined, PCs = 1:10, pN = 0.25, pK = 0.09, nExp = nExp_poi.adj, reuse.pANN = FALSE, sct = FALSE)
Error in doubletFinder_V3(BM16216.combined, PCs = 1:10, pN = 0.25, pK = 0.09,  : 
  could not find function "doubletFinder_V3"
> sweep.res.list_BM16216 <- paramSweep_v3(BM16216.combined, PCs = 1:20, sct = FALSE)
Error in paramSweep_v3(BM16216.combined, PCs = 1:20, sct = FALSE) : 
  could not find function "paramSweep_v3"

Thank you for help!

**Comment by eegk** [comment]
Same on my end.

> sweep.res.list <- paramSweep(seu = seuratV5, PCs = 1:10, sct = FALSE)
Error in .subscript.2ary(x, , j, drop = TRUE) : subscript out of bounds
In addition: Warning message:
In LayerData.Assay5(object = x, layer = i) :
  multiple layers are identified by counts.1 counts.2 counts.3 counts.4 counts.5 counts.6 counts.7 counts.8 counts.9 counts.10 counts.11 counts.12 counts.13 counts.14 counts.15 counts.16 counts.17 counts.18 counts.19 counts.20
 only the first layer is used

**Comment by imrankhan27** [comment]
Hello, I am having a similar issue. My DoubletFinder code used to work when I had an earlier version of Seurat than Seurat v5. 
packageVersion("DoubletFinder")
[1] ‘2.0.3’
but now both paramSweep(Seu, PCs = 1:20, sct = FALSE) and paramSweep_V3(Seu, PCs = 1:20, sct = FALSE) giving me this error messages: 
"Error in paramSweep(Seu, PCs = 1:20, sct = FALSE) : 
  unused argument (sct = FALSE)" 
and 
"Error in paramSweep_v3(Seu, PCs = 1:20, sct = FALSE) : 
  no slot of the name "counts" for this object of class "Assay5". 
Should I downgrade Seurat to make it work?
Appreciated!

**Comment by goldpm1** [comment]
Hi. I',m also encountering similar troubleshooting even though I updated the newest 2.0.4 version.

`> paramSweep( obj, PCs = 1:20, sct = FALSE)`

[1] "Creating artificial doublets for pN = 5%"
[1] "Creating Seurat object..."
[1] "Normalizing Seurat object..."
Normalizing layer: counts
Error in orig.commands$NormalizeData.RNA@params : 
  no applicable method for `@` applied to an object of class "NULL"

Thank you.

**Comment by DiegoSafian** [comment]
this error is still happening:
Error in paramSweep_v3(sc_data, PCs = 1:40, sct = FALSE) : 
  could not find function "paramSweep_v3"

**Comment by Jinyulin515** [comment]
I still have the same issue. Any update on it?

**Comment by DiegoSafian** [comment]
Hi, yes... I just removed "v3" and run it like:
 paramSweep(sc_data, PCs = 1:40, sct = FALSE)

**Comment by xubiy** [comment]
> Hi. I',m also encountering similar troubleshooting even though I updated the newest 2.0.4 version.
> 
> `> paramSweep( obj, PCs = 1:20, sct = FALSE)`
> 
> [1] "Creating artificial doublets for pN = 5%" [1] "Creating Seurat object..." [1] "Normalizing Seurat object..." Normalizing layer: counts Error in orig.commands$NormalizeData.RNA@params : no applicable method for `@` applied to an object of class "NULL"
> 
> Thank you.

I encountered the same error as well. :(

**Comment by xubiy** [comment]
> Hi. I',m also encountering similar troubleshooting even though I updated the newest 2.0.4 version.
> 
> `> paramSweep( obj, PCs = 1:20, sct = FALSE)`
> 
> [1] "Creating artificial doublets for pN = 5%" [1] "Creating Seurat object..." [1] "Normalizing Seurat object..." Normalizing layer: counts Error in orig.commands$NormalizeData.RNA@params : no applicable method for `@` applied to an object of class "NULL"
> 
> Thank you.



> Hi. I',m also encountering similar troubleshooting even though I updated the newest 2.0.4 version.
> 
> `> paramSweep( obj, PCs = 1:20, sct = FALSE)`
> 
> [1] "Creating artificial doublets for pN = 5%" [1] "Creating Seurat object..." [1] "Normalizing Seurat object..." Normalizing layer: counts Error in orig.commands$NormalizeData.RNA@params : no applicable method for `@` applied to an object of class "NULL"
> 
> Thank you.

If you used SCTransform for pre-processing, then you should change 'sct = FALSE' to 'sct = TRUE'.

**Comment by studentYem** [comment]
sweep.res.list <- paramSweep(sc_E12.5, PCs = 1:30)
Error in ncol(seu@data) : 
  no slot of name "data" for this object of class "Seurat". There is still something wrong with it.
![Uploading 1714710760554.jpg…]()

**Comment by haibol2016** [comment]
Change https://github.com/chris-mcginnis-ucsf/DoubletFinder/blob/master/R/paramSweep.R#L18
to 
`
if ( Version(seu)== "v3") {
      data <- seu@assays$RNA$counts[ , real.cells]
} else if (Version(seu)== "v5") {
     data <- seu@assays$RNA@layers$counts[ , real.cells]
}
`
It will work.

**Comment by BERICP01** [comment]
Hello, any update regarding this issue?
I am encountering as well the same problem with the latest versions of DoubletFinder and Seurat5.
Thanks

**Comment by KylonisThanos** [comment]
i do have the same issue "Error in paramSweep_v3(sample0_filtered, PCs = 1:30, sct = FALSE) : 
  no slot of name "counts" for this object of class "Assay5"
Execution halted"

**Comment by haibol2016** [comment]
@KylonisThanos 

   Have you tried the latest version of DoubletFinder v2.0.6?  I think this issue has been solved by https://github.com/chris-mcginnis-ucsf/DoubletFinder/blob/master/R/paramSweep.R#L42-L46. Let me know if you still have the issue after install the latest version.

Haibo

**Comment by ModupeOjo** [comment]
Help: I am having issues just running the examples from the package
### ** Examples


data(pbmc_small)
seu <- pbmc_small
nExp_poi <- round(0.15*nrow(seu@meta.data))
seu <- doubletFinder(seu, PCs = 1:10,
pN = 0.25, pK = 0.01,
nExp = nExp_poi,
reuse.pANN = FALSE, sct=FALSE)
Error in xtfrm.data.frame(x): cannot xtfrm data frames
## With homotypic adjustment
annotations <- seu$RNA_snn_res.1
homotypic.prop <- modelHomotypic(annotations)
nExp_poi.adj <- round(nExp_poi*(1-homotypic.prop))
seu <- doubletFinder(seu, PCs = 1:10, pN = 0.25,
                     pK = 0.01, nExp = nExp_poi.adj,
                     reuse.pANN = FALSE,
                     sct=FALSE)
Error in xtfrm.data.frame(x): cannot xtfrm data frames

**Comment by yukixuen** [comment]
> [@KylonisThanos](https://github.com/KylonisThanos)
> 
> Have you tried the latest version of DoubletFinder v2.0.6? I think this issue has been solved by https://github.com/chris-mcginnis-ucsf/DoubletFinder/blob/master/R/paramSweep.R#L42-L46. Let me know if you still have the issue after install the latest version.
> 
> Haibo

Help! I've confirmed the latest version v2.0.6, which has already removed the function "paramSweep_v3" and only left the function "paramSweep", but the error is still here:

>   sweep.res   <- paramSweep(obj, PCs = 1:30, sct = FALSE)
Error:
! The `slot` argument of `GetAssayData()` was deprecated in SeuratObject 5.0.0 and is now defunct. Please use the `layer` argument instead.

**Comment by yukixuen** [comment]
> > [@KylonisThanos](https://github.com/KylonisThanos)
> > Have you tried the latest version of DoubletFinder v2.0.6? I think this issue has been solved by https://github.com/chris-mcginnis-ucsf/DoubletFinder/blob/master/R/paramSweep.R#L42-L46. Let me know if you still have the issue after install the latest version.
> > Haibo
> 
> Help! I've confirmed the latest version v2.0.6, which has already removed the function "paramSweep_v3" and only left the function "paramSweep", but the error is still here:
> 
> > sweep.res   <- paramSweep(obj, PCs = 1:30, sct = FALSE)
> > Error:
> > ! The `slot` argument of `GetAssayData()` was deprecated in SeuratObject 5.0.0 and is now defunct. Please use the `layer` argument instead.

I've found that this error happened because I had loaded a seurat object of Seurat v4. Nothing wrong with DoubletFinder now. Thanks!

**Comment by KylonisThanos** [comment]
> [@KylonisThanos](https://github.com/KylonisThanos)
> 
> Have you tried the latest version of DoubletFinder v2.0.6? I think this issue has been solved by https://github.com/chris-mcginnis-ucsf/DoubletFinder/blob/master/R/paramSweep.R#L42-L46. Let me know if you still have the issue after install the latest version.
> 
> Haibo

Yes everything alright! Thank you mate!
