### ISSUE TITLE
Can I perform doublet finder on merge seurat object? 

### ISSUE THREAD

**Issue by synatkeamsk** [chris-mcginnis-ucsf/DoubletFinder#174]
Dear Authors, 

I am wondering whether I could perform doublet finder on merge Seurat object (not integrated object) rather than individual sample. if that is possible, how could I estimate the percentage of doublet cells in the merge object as there will be a a lot of cells in the merge object?  

Kind Regards,

Synat

**Comment by Fattigman** [comment]
You should only perform doublet detection on individual sequencing libraries. You could just loop through your original data identities and run doubletfinder on each one. 
If you are using 10X library you can use this chart for reference for the percentage estimation: https://kb.10xgenomics.com/hc/en-us/articles/360054599512-What-is-the-cell-multiplet-rate-when-using-the-3-CellPlex-Kit-for-Cell-Multiplexing-
