### ISSUE TITLE
Can you provide the old version 2.0.3

### ISSUE THREAD

**Issue by RunhanZhao** [chris-mcginnis-ucsf/DoubletFinder#186]
Dear author,  
    we still use Seurat v.4, for finishing our project. We really need the old version 2.0.3. So we hope you provide the install package. Thank you so much.

**Comment by feather-W** [comment]
Hi,

I also need the old version 2.0.3. Could you please tell me how can I get the old version 2.0.3?

Thank you very much!

**Comment by feather-W** [comment]
> Hi,
> 
> I also need the old version 2.0.3. Could you please tell me how can I get the old version 2.0.3?
> 
> Thank you very much!

Ok, I got the old version 2.0.3 from the following link:
https://github.com/chris-mcginnis-ucsf/DoubletFinder/issues/175
