### ISSUE TITLE
Add option to skip pN optimization

### ISSUE THREAD

**Issue by RoganGrant** [chris-mcginnis-ucsf/DoubletFinder#19]
Given that you have found pN optimization is largely unnecessary, would it be possible to update the paramSweep function to allow for a static pN?

**Comment by chris-mcginnis-ucsf** [comment]
Good question -- Even though pN is held constant when performing the final DoubletFinder run, varying pN is necessary for pK optimization. The updated manuscript (just accepted at Cell Systems, should be out in the next few weeks) will describe this in more detail. The core premise is that pK values that are too low are sensitive to local density fluctuations in artificial doublets, and varying pN captures this effect.

**Comment by RoganGrant** [comment]
Ah, makes sense. Thanks for the quick response!
