### ISSUE TITLE
summarizeSweep crashes when all pANN=0

### ISSUE THREAD

**Issue by sorrge** [chris-mcginnis-ucsf/DoubletFinder#21]
The function summarizeSweep cannot handle cases when all pANN values for a certain parameter set are 0. It gives the following error message:

> Error in if (L == 0) warning("Binning grid too coarse for current (small) bandwidth: consider increasing 'gridsize'") :
>   missing value where TRUE/FALSE needed

This is because bkde function from KernSmooth cannot deal with singular input. You need to treat this as a special case.

Also, is it a sign of some kind of problem when all pANN are 0 for some parameters? In my case, all pN=0.3 give all-zero pANN, as well as some other combinations. This seems suspicious to me. If this is the case, it is worth notifying the user about this problem and possible causes.

**Comment by sorrge** [comment]
After some debugging, I have traced the problem to the line

>    PCs <- seu@commands$RunTSNE.pca$dims

in paramSweep_v3(). seu@commands$RunTSNE.pca is not defined, seu@commands$RunTSNE is defined instead. Then PCs were set to Null, and the distance calculations silently failed, filling the distance matrix with garbage. Enjoy R.

Perhaps it's not a great idea to grab parameters from such obscure places, why not make it a parameter of the paramSweep_v3() function? This will also remove the need to run tSNE, which is only needed for the purpose of taking this parameter - a truly bizarre solution.

**Comment by Guillermo-Rivera** [comment]
I am experiencing the same error when running summarizeSweep:

Error in if (L == 0) warning("Binning grid too coarse for current (small) bandwidth: consider increasing 'gridsize'") : missing value where TRUE/FALSE needed

I am running SeuratV3 and paramSweepv3 ran without issues

**Comment by danielruss** [comment]
I am also running into the same issue.  In my case I don't create a TSNE, I use UMAP to visualize the data in 2 dimensions.

**Comment by chris-mcginnis-ucsf** [comment]
Followed the suggestion from sorrge to make PCs a user-defined argument in doubletFinder, doubletFinder_v3, paramSweep, and paramSweep_v3 -- I agree, requiring tSNE was a tad 'bizarre'. 

Let me know if this fixes your issues, @Guillermo-Rivera and @danielruss 

Chris

**Comment by danielruss** [comment]
@chris-mcginnis-ucsf  @Guillermo-Rivera  and my error were in the summarizeSweep step, not the param_sweep_v3 function.  I don't see any changes (other than whitespace changes in the function).  I'll try and debug it when I have some time, but this fix is not solving the problem.  

Also, try length(obj@reductions$pca) to get the number of PCs calculated.

**Comment by sorrge** [comment]
There are some more issues with the latest changes: @chris-mcginnis-ucsf  , please recheck the upper/lowercase file names. There are now files ending with "_V3" and "_v3" in the repo. Probably the original code is still working and causing the problem.

@danielruss if your problem is the same as mine, which is almost surely the case since you said you use UMAP instead of t-SNE, then it actually occurs in summarizeSweep. It fails silently, so you don't notice it until the data generated there is used in param_sweep_v3, which then crashes. It fails because it needs to know the number of PCs to use, which it tries to take from t-SNE info. If you didn't do t-SNE, then the info is not there, but instead of crashing at this obvious failure point, R developers decided that it's more fun to return NULL instead. Then the distance calculation is also doing something with the NULL-dimensional space... It's worse than Javascript horror stories really.

**Comment by chris-mcginnis-ucsf** [comment]
@sorrge, good catch. I've removed the mis-named files and successfully tested the functions on my own dataset. Let me know if you all continue to run into issues.

Chris

**Comment by preetida** [comment]
Hi, 
I have similar issue with 
`> sweep.stats_b <- summarizeSweep(sweep.res.list_bmr, GT = FALSE)
Loading required package: modes
Error in if (L == 0) warning("Binning grid too coarse for current (small) bandwidth: consider increasing 'gridsize'") : 
  missing value where TRUE/FALSE needed
In addition: Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
 
 Error in if (L == 0) warning("Binning grid too coarse for current (small) bandwidth: consider increasing 'gridsize'") : 
  missing value where TRUE/FALSE needed `

Also, I have UMAP in my serurat object 
```
> bmr 
An object of class Seurat 
27998 features across 30543 samples within 1 assay 
Active assay: RNA (27998 features, 2000 variable features)
 2 dimensional reductions calculated: pca, umap
```

**Comment by chris-mcginnis-ucsf** [comment]
Hi @preetida 

Sorry to see you're having issues. Couple of questions:

1. Does paramSweep_v3 finish without errors? Could you show me a snapshot of head(sweep.res.list_bmr) ?
2. Does SCTransform fail on your normal dataset? Or just when you try to do paramSweep_v3?

Also, I only check this github every couple of weeks, so if you want to start a dialog, feel free to reach out to me directly (chris.mcginnis@ucsf.edu)

Chris

**Comment by preetida** [comment]
Hi Chris, 
Thank you for getting back to me. 
Here is the answers for your questions. 
1. yes paramSweep_v3 finished without error. Here is the snapshot of 
````
std4_CACACAACACTACAGT    0
std2_TTAACTCCAGCGTCCA    0
std3_GGGCACTAGAAACGCC    0
std1_GGCGTGTTCTTTACGT    0
std1_ACGGAGAGTGCTTCTC    0
std7_GAAACTCTCTCTTGAT    0
`````
2. SCTransform works, but after running SCTransform, paramSweep_v3 fails.

**Comment by preetida** [comment]
Hi Chris,
Thank you for getting back to me.

Sorry, it took me long to get back to this issue.  I would greatly
appreciate it if you can help me debug this.

Here are the answers to your questions.

   1. yes, paramSweep_v3 finished without error. Here is the snapshot of

std4_CACACAACACTACAGT    0
std2_TTAACTCCAGCGTCCA    0
std3_GGGCACTAGAAACGCC    0
std1_GGCGTGTTCTTTACGT    0
std1_ACGGAGAGTGCTTCTC    0
std7_GAAACTCTCTCTTGAT    0


   1. SCTransform works, but after running SCTransform, paramSweep_v3 fails.


Also attached here the script I am running for doublet finder.
Any leads would be appreciated.

thanks.
Preeti

Preetida  J.  Bhetariya, Ph.D.
Bioinformatics Analyst / RA
Bioinformatics Core
Harvard T.H. Chan School of Public Health
http://bioinformatics.sph.harvard.edu/
(M) : 815-909-8373
