### ISSUE TITLE
Unable to use new functions for Seurat V3

### ISSUE THREAD

**Issue by koetjen** [chris-mcginnis-ucsf/DoubletFinder#22]
I installed DoubletFinder today, but am not able to use the paramSweep_V3 and doubletFinder_V3 functions. Thanks for any help you can provide.

> library(DoubletFinder)
> sweep.res.list_MDS <- paramSweep_V3(MDS.list[[1]])
Error in paramSweep_V3(MDS.list[[1]]) : 
  could not find function "paramSweep_V3"
> session_info()
─ Session info ──────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.5.2 (2018-12-20)
 os       macOS Mojave 10.14.3        
 system   x86_64, darwin15.6.0        
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       America/Chicago             
 date     2019-04-05                  
...
 DoubletFinder        * 2.0.0      2019-04-05 [1] Github (chris-mcginnis-ucsf/DoubletFinder@6643b82)

**Comment by koetjen** [comment]
sorry, just saw that it should be  paramSweep_v3. will close the issue.

**Comment by ling-lyang** [comment]
How was this resolved? I encountered the same issue.
