### ISSUE TITLE
what annotation file should be load?

### ISSUE THREAD

**Issue by wangjingwan** [chris-mcginnis-ucsf/DoubletFinder#25]
what annotation file should be fill here? 
homotypic.prop <- modelHomotypic(**annotations**)
I added 'pbmc@active.ident' , is that correct? 
And I noticed that the number of finally detected doublet is set to 0.075*cell number. Is 0.075 based on your experience?

**Comment by chris-mcginnis-ucsf** [comment]
Hi wangjingwan,

Your solution for annotations should work -- you can specify any particular annotation vector for this function (e.g., clustering results, manual annotations, etc.). I've adjusted the readme to make this more clear.

As for the specified 7.5% doublet rate, this was specific to the doublet formation rate from the kidney dataset used in the Cell Systems paper. You should replace '0.075' with whatever doublet formation rate is expected from your particular 10X cell loading density. I've adjust the readme to make this more clear, as well.

Notably, this step does not actually change the raw pANN values you get for each cell after running doubletFinder() -- rather, it just determines where the pANN distribution is thresholded to make the final doublet predictions. So if you do not have a good estimate for the doublet formation rate, I would suggest either (A) Scanning through a few pANN thresholds (using the reuse.pANN argument in doubletFinder() ) and seeing which cell clusters are robustly defined as doublets or (B) using Scrublet.

Chris
