### ISSUE TITLE
Error in pca.results$u %*% diag(pca.results$d): non-conformable arguments

### ISSUE THREAD

**Issue by nixstix** [chris-mcginnis-ucsf/DoubletFinder#27]
Hi,

Thanks for the tool - I am looking forward to trying it. I am running into an issue early on. I have a Seurat2 object. When I run `param_sweep(seuratObj, PCs=10)`, I get the following error:
```Error in pca.results$u %*% diag(pca.results$d): non-conformable arguments
Traceback:

1. paramSweep(novaS2, PCs = 10)
2. RunPCA(seu_wdoublets, pc.genes = seu_wdoublets@var.genes, pcs.print = 0, 
 .     pcs.compute = length(PCs))
```
Any idea where the problem could lie?

Thanks in advance!

**Comment by chris-mcginnis-ucsf** [comment]
Should be PCs = 1:10 instead of PCs = 10.
