### ISSUE TITLE
Use a different transformation method (ex : sctransform)

### ISSUE THREAD

**Issue by JonathanCruard** [chris-mcginnis-ucsf/DoubletFinder#29]
Hi,
I'm actually testing multiple tools for scRNAseq analysis.
My actual pipeline is working with [sctransform](https://github.com/ChristophH/sctransform) instead of the standard Seurat workflow. I've found a way to make it work with your tool.
But do you plan to allow the user to choose the normalization method?
Thanks,
JonathanCruard

**Comment by chris-mcginnis-ucsf** [comment]
Hi JonathanCruard, 

I actually just added this functionality last week. Just set sct=T in paramSweep_v3 and doubletFinder_v3.

Chris

**Comment by JonathanCruard** [comment]
Thanks for the quick answer Chris. Sorry for the bad question. Just need to update my local installation so.
Best,
JonathanCruard
