### ISSUE TITLE
Raw data selection when starting from subsetted Seurat object & error if PCs of original object >20

### ISSUE THREAD

**Issue by gabprg** [chris-mcginnis-ucsf/DoubletFinder#3]
Hi there!

I wanted to report 2 minor points/issues:
1) If you start from a Seurat object which was created using the SubsetData function, the raw.data slot contains the raw data from the full object - this means that the new Seurat object will contain everything which was present in the initial dataset.
2) The RunPCA function by default only computes 20 PCs. If the original Seurat object used more, this causes an error since the ones >20 are out of bounds in the new object containing doublets. This could also easily be adjusted by either automatically computing a larger number of PCs (pcs.compute) or having this parameter as an option.

I hope this makes sense. Thanks!!!

Gabriela

**Comment by chris-mcginnis-ucsf** [comment]
Great, thanks for informing us! Will fix and update code ASAP.
