### ISSUE TITLE
DEG analysis considering DoubleFinder results

### ISSUE THREAD

**Issue by tkapello** [chris-mcginnis-ucsf/DoubletFinder#30]
Hi,

      I wanted to ask how one can calculate DE genes between tSNE clusters in a Seurat object upon removal of doublet cells,

Best,
Theo

**Comment by chris-mcginnis-ucsf** [comment]
Hi Theo,

Perhaps I'm misunderstanding your question... I would perform DEG analysis just as normal, except with a newly-processed Seurat object that no longer contains doublets. For more information on DEG analysis in Seurat, see their tutorials: https://satijalab.org/seurat/get_started.html

Let me know if this answers your question,
Chris
