### ISSUE TITLE
memory issue

### ISSUE THREAD

**Issue by lo2811** [chris-mcginnis-ucsf/DoubletFinder#33]
Hi Chris,
I tested DoubletFinder_v3 on 1 sample and got promising result. Now I am trying to use DoubletFinder_v3 for my combined object (40 samples, size ~12GB). I ran it on our cluster with 200GB memory and my job was killed by R all the time due to too much memory.
Here is the code:
seu <- doubletFinder_v3(seu, PCs = 1:10, pN = 0.25, pK = pk, nExp = nExp_poi, reuse.pANN = FALSE, sct = T)
Do you have any suggestions for a better approach? 
Thanks,
Linh

**Comment by chris-mcginnis-ucsf** [comment]
Hi Linh,

Sorry to hear you've been having memory issues. I would have to comb through my code to make it more efficient -- which is something I've been meaning to do, but is on the back-burner at the moment. 

I'll say that Seurat objects processed using SCTransform are a LOT bigger than those processed using the standard pipeline (e.g., NormalizeData --> ScaleData --> FindVariableFeatures). So if you want more immediate results, you may consider finding doublets on a non-SCT-processed version of your data, which shouldn't have the same memory issues on your cluster.

With that being said, assuming that your 40 samples consist of _different_ subsets of cells (this assumption is incorrect if you sequenced the same cell pool across 40 10X lanes***), then you will want to run DoubletFinder on each lane individually (or, perhaps after merging replicate lanes). The reason for this is that running DoubletFinder on the merged dataset will cause DoubletFinder to make artificial doublets representing real doublets that could not possibly exist in your data. 

For example, if your 40 samples correspond to 40 different 1-day differentiation time-points, then DoubletFinder will try to find doublets from D0 and D40 cells, which shouldn't exist.

Let me know if you have any other questions,

Chris

*** Tangentially, if you are indeed sequencing 40 10X lanes-worth of data, then I would recommend you look into some of the recently described sample multiplexing approaches (e.g., Demuxlet, Cell Hashing, and MULTI-seq). Would let you do the same experiment except (perhaps, depending on how many cells you need per sample) for 40-times less $$$.

**Comment by lo2811** [comment]
Hi Chris,

Thank you for your suggestion!

I followed your suggestions: using the standard pipeline (NormalizeData --> ScaleData --> FindVariableFeatures) and I still got the same error though. We are doing scRNAseq for a lot of samples from patient's biopsy, so in the future our Seurat object will be even bigger.

Best,
Linh

**Comment by chris-mcginnis-ucsf** [comment]
Hi again Linh, 

I'll reiterate the point I made above -- you need to run DoubletFinder on each scRNA-seq sample individually. Otherwise, DoubletFinder will make artificial doublets that do not actually reflect any real data point. This will influence your results dramatically (in a bad way).  Moreover, running DoubletFinder on individual data subsets will address your memory issue. 

Chris
