### ISSUE TITLE
expected doublet rate

### ISSUE THREAD

**Issue by hwlim** [chris-mcginnis-ucsf/DoubletFinder#34]
Hi

I am currently following your "Example code for 'real-world' applications".
Does it always find a fixed number of doublets?

The example code first find the fixed number of doublets based on the "expected doublet rate" in
>  Exp_poi <- round(doubletRatio.expected * length(Cells(seurat)))
>  seurat <- doubletFinder(seurat, PCs = 1:10, pN = 0.25, pK = 0.09, nExp = nExp_poi, reuse.pANN = FALSE)
The numbero doublets seems to be always the same with the expected number from my own manual parameter, "doubletRatio.expected". 

Then, it identifies high confident doublets among them by
> nExp_poi.adj <- round(nExp_poi*(1-homotypic.prop))
> seurat <- doubletFinder(seurat, PCs = 1:10, pN = 0.25, pK = 0.09, nExp = nExp_poi.adj, reuse.pANN = "pANN_0.25_0.09_913")

It seems like the expected doublet rate is a critical parameter. Can I get some advice about how to set it? or please let me know if my understanding is wrong.

Thank you.

**Comment by chris-mcginnis-ucsf** [comment]
Hi hwlim,

No, DoubletFinder doesn't always find a fixed number of doublets. It finds the number of doublets you tell it to using the 'nExp' argument -- in your example, nExp_poi. After running DoubletFinder the first time, it saves the pANN values and list of classifications to new columns in the metadata that record the three key DoubletFinder parameters: pN, pK, and the # of doublets. Thus, if you want to adjust the results to account for homotypic doublets, you specify this column name in the 'reuse.pANN' argument. 

As for your second question, we suggest setting the expected doublet rate according to the density of cells you loaded into the 10x microfluidics chip. See the 10x user guide for the doublet formation rates associated with each cell loading density.

**Comment by hwlim** [comment]
Hi. Thank you so much for the kind explanation. That was really helpful!
