### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by JennyWeng** [chris-mcginnis-ucsf/DoubletFinder#39]
Hi,
I am trying to install this package using the following code:
devtools::install_github('chris-mcginnis-ucsf/DoubletFinder')
however, I get an error message like this:

Downloading GitHub repo chris-mcginnis-ucsf/DoubletFinder@master
Error: HTTP error 422.
  No commit found for SHA: release/3.0

  Rate limit remaining: 57/60
  Rate limit reset at: 2019-06-21 11:00:20 UTC

Do you have any suggestions about how can I solve this problem? Thank you very much!

**Comment by chris-mcginnis-ucsf** [comment]
Fixed -- something weird with requiring Seurat import while intalling DoubletFinder. I removed this import requirement and it should now install smoothly.

Thanks for bringing this to my attention!

Chris
