### ISSUE TITLE
BCmvn keeps increases

### ISSUE THREAD

**Issue by chansigit** [chris-mcginnis-ucsf/DoubletFinder#43]
I can't see a single-peak after running paramSweep_v3
the BCmetric is increasing as pK increases
which pK shall I choose?

The bcmvn i got are:
ParamID | pK | MeanBC | VarBC | BCmetric
1 | 0.005 | 0.6322526 | 0.0062336671 | 101.42546
2 | 0.01 | 0.6314945 | 0.0043372477 | 145.59797
3 | 0.02 | 0.6406362 | 0.0072198519 | 88.73260
4 | 0.03 | 0.6560862 | 0.0083522676 | 78.55187
5 | 0.04 | 0.6724027 | 0.0067474174 | 99.65335
6 | 0.05 | 0.6764357 | 0.0066137246 | 102.27757
7 | 0.06 | 0.6784079 | 0.0074017078 | 91.65560
8 | 0.07 | 0.6799124 | 0.0072759030 | 93.44714
9 | 0.08 | 0.6813135 | 0.0072258698 | 94.28809
10 | 0.09 | 0.6811553 | 0.0079572110 | 85.60226
11 | 0.1 | 0.6798985 | 0.0090639511 | 75.01127
12 | 0.11 | 0.6894440 | 0.0084931059 | 81.17690
13 | 0.12 | 0.6904313 | 0.0102618693 | 67.28124
14 | 0.13 | 0.6963331 | 0.0093759757 | 74.26780
15 | 0.14 | 0.6995890 | 0.0097656529 | 71.63771
16 | 0.15 | 0.7064218 | 0.0089377553 | 79.03794
17 | 0.16 | 0.7099229 | 0.0089569153 | 79.25975
18 | 0.17 | 0.7130803 | 0.0084972736 | 83.91872
19 | 0.18 | 0.7191425 | 0.0078496397 | 91.61471
20 | 0.19 | 0.7274438 | 0.0065485259 | 111.08512
21 | 0.2 | 0.7332291 | 0.0052203877 | 140.45491
22 | 0.21 | 0.7420419 | 0.0039294137 | 188.84290
23 | 0.22 | 0.7478681 | 0.0031535904 | 237.14815
24 | 0.23 | 0.7499830 | 0.0028707247 | 261.25215
25 | 0.24 | 0.7517944 | 0.0028600436 | 262.86118
26 | 0.25 | 0.7542440 | 0.0020662547 | 365.02952
27 | 0.26 | 0.7596140 | 0.0014461647 | 525.26108
28 | 0.27 | 0.7642677 | 0.0009825212 | 777.86381
29 | 0.28 | 0.7678856 | 0.0006758615 | 1136.15822
30 | 0.29 | 0.7678427 | 0.0005725801 | 1341.02242
31 | 0.3 | 0.7684884 | 0.0004597986 | 1671.35856

Thanks for your help!

**Comment by chris-mcginnis-ucsf** [comment]
Hi! Apologies for the delayed response. Some questions:

1. How did you pre-process your data prior to running DoubletFinder? I sometimes see strange BCmvn distributions if the initial dataset includes low-quality cells.

2. What type of cells are you analyzing? BCmvn results are often difficult to choose a pK value when applied to datasets where DoubletFinder doesn't work very well (i.e., transcriptionally homogenous systems).

**Comment by diala-ar** [comment]
Thanks for the nice package! I also have a similar problem, getting high pks while data does not contain low-quality or dead cells and my samples are made of heterogeneous cell types. Any idea what could be the problem? Should I conclude that DoubletFinder does not perform well on my dataset or is there any other suggestion?

![image](https://user-images.githubusercontent.com/9170319/228569419-558ec572-f49c-4e5c-a9db-89e36bc05714.png)

Thanks.
