### ISSUE TITLE
elapsed time of using SCTransform

### ISSUE THREAD

**Issue by zehualilab** [chris-mcginnis-ucsf/DoubletFinder#46]
Thanks for the convenient tools to detect the doublets!
I met the problem when runing:
sweep.res.list_seurat <- paramSweep_v3(seurat, PCs = 1:75, sct = T)
Should this step take a long time to run? My desktop computer did not finish running it in 24h with the R console filled with the mesages of SCTransform.
Like this:
[1] "Creating artificial doublets for pN = 5%"
Loading required package: sctransform
[1] "Creating Seurat object..."
[1] "Running SCTransform..."
Calculating cell attributes for input UMI matrix
Variance stabilizing transformation of count matrix of size 15867 by 6415
Model formula is y ~ log_umi
Get Negative Binomial regression parameters per gene
Using 2000 genes, 6415 cells
  |==================================================================================================================================| 100%non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = ...............

**Comment by chris-mcginnis-ucsf** [comment]
Did you end up figuring this out?

This is certainly the slowest step of the workflow, but it shouldn't take that long, assuming you have sufficient computing power. I don't know if it is taking longer because you are using so many PCs? Notably, if you only have ~6K cells in your dataset, I'm guessing that this is WAY too many PCs to use. I've run this on similar-sized datasets to yours and this step takes 30min-1hr.

**Comment by zehualilab** [comment]
No, I didn't. I believe it might be due to the overload of the messeages from SCTransform, which slows down the R process. My CPU did not work hard when running this. I believe there might be thousands of lines of messages like this and the console failed to print more.

**Comment by chris-mcginnis-ucsf** [comment]
Did you end up figuring this out?

**Comment by zehualilab** [comment]
Yes, I just figured this out. It worked well in R file but not in a RMD file.

**Comment by ryland-mortlock** [comment]
Hi, I also notice the same issue when trying to run DoubletFinder in an R markdown. The same type of messages pop up for me and the algorithm cannot run either the paramSweep or the doubletFinder functions. I moved the analysis out of my R markdown, cached the result, then moved back in. But I have never seen this type of problem before with any other algorithms.
