### ISSUE TITLE
Script Tutorial for SEURAT Object V3

### ISSUE THREAD

**Issue by EDYAC** [chris-mcginnis-ucsf/DoubletFinder#50]
Dear All,
Thank you so much for this interesting paper and package.
I was wondering if there was any tutorial easy to follow for those that aren't very good at coding.
I'm using Seurat V3
Thank you.

**Comment by chris-mcginnis-ucsf** [comment]
Hi EDYAC,

The tutorial in the readme assume Seurat V3 (that is what the 'v3' in the functions refers to)

Chris
