### ISSUE TITLE
Doublets versus Phagocytic Macrophages

### ISSUE THREAD

**Issue by EDYAC** [chris-mcginnis-ucsf/DoubletFinder#51]
Hi All,
I work on immune cells, as you know macrophages are phagocytic, they can eat other cells.
When I analyse macropahges, a cluster of them express markers of other immune cells, like T cells.
Do you think using, your tool can differentiate between the two? I mean between a doublet and between a macrophages that ate a T cell.
Thank you

**Comment by chris-mcginnis-ucsf** [comment]
Interesting question... Determining whether DoubletFinder is sensitive to such events would require a dataset where phagocytic interactions are known. I don't know of any such datasets, and my gut says that DoubletFinder would not be sensitive to these 'cells'.
