### ISSUE TITLE
paramSweep_v3 error

### ISSUE THREAD

**Issue by Jiam1ng** [chris-mcginnis-ucsf/DoubletFinder#53]
hi, when useparamSweep_v3, it reports error:
`Error in NormalizeData.default(object = GetAssayData(object = object, : trying to get slot "params" from an object of a basic class ("NULL") with no slots`
but when I set sct argument to TRUE, it just worked fine, the question is  I didn't use SCTransform to normalize my data, is this a normal thing to see?

**Comment by Jiam1ng** [comment]
I was using a integrated data, and I found that it's not reasonable to filter doublets based on integrated data, I think I can close the issue now

**Comment by GBeattie** [comment]
Hey, getting the same error with the same command, but for different reasons. Seems to depend on whether SCTransform has been used (although I have 2 samples, one with 11,000 cells which worked with SCT, another with 5,000 cells which didn't)

So, for the 5,000 cell sample, this didn't work:

```
  seu.list[[samp]] <- seu.list[[samp]] %>% SCTransform %>% RunPCA()
  sweep <- paramSweep_v3(seu.list[[samp]], PCs = 1:10, sct = T)
```

with the last few lines of the error being: 
```
[1] "pK = 0.29..."
[1] "pK = 0.3..."
NULL
[1] "Creating 3662 artificial doublets..."
[1] "Creating Seurat object..."
[1] "Normalizing Seurat object..."
Error in NormalizeData.default(object = GetAssayData(object = object,  : 
  trying to get slot "params" from an object of a basic class ("NULL") with no slots
In addition: There were 50 or more warnings (use warnings() to see the first 50)
```

but this did work:
```
  seu.list[[samp]] <- seu.list[[samp]] %>% NormalizeData() %>% FindVariableFeatures() %>% ScaleData() %>% RunPCA()
  sweep <- paramSweep_v3(seu.list[[samp]], PCs = 1:10, sct = F)
```
