### ISSUE TITLE
modelHomotypic in Seurat 3

### ISSUE THREAD

**Issue by Jiam1ng** [chris-mcginnis-ucsf/DoubletFinder#54]
Hi, I was using DoubletFinder with Seurat3, but when I estimate homotypic rate, it turns out that nExp_poi.adj value is negative, and I went to see the R code of modelHomotypic:
`modelHomotypic <- function(annotations) {
  anno.freq <- table(annotations)/length(annotations)
  x <- sum(anno.freq^2)
  return(x)
}
`
I wonder if length(annotations) also means the cell numbers? cause in Seurat3, length(object[["cluster"]]) is 1, if I change this to dim(object[["cluster"]])[1], nExp_poi.adj is a normal value between 0 and 1.

**Comment by chris-mcginnis-ucsf** [comment]
You need to submit a vector of annotations for the modelHomotypic function. For example, to use the active identity of my Seurat object as my annotations, I would do:

anno.freq <- as.character(seu@active.ident)

My guess is that you are using something else for the annotations variable and this is messing up the results.
