### ISSUE TITLE
Dependence on perplexity

### ISSUE THREAD

**Issue by knoedlerj** [chris-mcginnis-ucsf/DoubletFinder#55]
Just a question - I'm working with a highly heterogeneous population and haven't quite decided the right level of resolution. How dependent is the % doublet detection on the number of annotated clusters (i.e. if you chose a low resolution and the dataset contains 20 clusters, will you find a drastically different doublet percentage if you increase resolution and find 40)?

**Comment by chris-mcginnis-ucsf** [comment]
The clustering resolution will determine how much the poisson doublet formation rate is adjusted to account for homotypic doublet formation. I would try adjusting the expected doublet rate using different clustering resolutions and visually inspecting the DoubletFinder predictions for each resolution.
