### ISSUE TITLE
Example workflow

### ISSUE THREAD

**Issue by amjass12** [chris-mcginnis-ucsf/DoubletFinder#57]
Hello! I am interested in using this package however i was wondering if there is an example workflow?

I am little confused in the supplementary information from the cell systems paper that states the doubledetection starts with pre-processed data, but the steps in the first section take the data through to PCA and tsne cluster detection in the seurat pipeline. please can you clarify?

Also, can you show an example of how to split the seurat object in to their different batches (i.e individual 10x lanes) and running doubletdetection on all individual batches simultaneously? 

does the seurat pipeline have to be re-run after this?

many thanks!

**Comment by chris-mcginnis-ucsf** [comment]
Example workflows are provided in the "Example code for 'real-world' applications" of the readme.
