### ISSUE TITLE
Error when using Seurat object that has higher PCs used than RunPCA default

### ISSUE THREAD

**Issue by FloWuenne** [chris-mcginnis-ucsf/DoubletFinder#6]
Hi there,

thanks for the great package and the really nice preprint. I really enjoyed reading the preprint and I think it is amazing that the implementation directly runs upon a Seurat object, since many people (myself included) work with Seurat directly. 

I ran into an issue when using the doubletFinder() function on a Seurat object for which more than 20 PCs (the default value) were used to perform the tSNE. 

I think I found the culprit for this, which is in line 66 and  of doubletFinder.R:

https://github.com/chris-mcginnis-ucsf/DoubletFinder/blob/6fb716b2ef9eded27e91fba884c0c413798c7d21/R/doubletFinder.R#L66

Which will select the number of PCs that were used in the original tSNE clustering.
To get the PCA coordinates though, we try to subset the PCs calculated in seu_wdoublets using the number of PCs used in the original Seurat object. If this number is >20 PCs, the following line:

https://github.com/chris-mcginnis-ucsf/DoubletFinder/blob/6fb716b2ef9eded27e91fba884c0c413798c7d21/R/doubletFinder.R#L70

will return a _subscript out of bounds_ error. 

I created a pull request in which I added pcs.compute to the RunPCS command so that the number of PCs that will be calculated corresponds to the number of PCs initially used in the original Seurat object.

Let me know if there are any problems with this or if there is a better way to implement this. 
Hope this helps,

Best,

Florian

**Comment by chris-mcginnis-ucsf** [comment]
Hi Florian, 

Thanks so much for the interest in doubletFinder + your fixes. I accepted the pull request and this bug should now be solved. 

Chris
