### ISSUE TITLE
SCTransform Question

### ISSUE THREAD

**Issue by jad362** [chris-mcginnis-ucsf/DoubletFinder#61]
Hi! I have a question about param_sweep_V3 and Doublet_Finder_v3.

When you set sct = TRUE does it cause SCTransform to be applied to the datasets or does it indicate that SCTransform was applied to the datatsets already? I've run the Seurat pipeline on my datatsets using SCTransform already and I'm worried about DoubletFinder renormalizing already normalized datasets.

Thanks for the clarification!

**Comment by chris-mcginnis-ucsf** [comment]
Hi, you set sct = T when the data has been normalized using SCTransform. This ensures that SCTransform is also used during the parameter sweep step.

**Comment by nandomgu** [comment]
why is sct=T causing sct transform to be recomputed at every step? shouldn't once be enough?
My seurat object already was SCT transformed. if I select sct=FALSE, then it gives me thi error

so <- doubletFinder_v3(so, PCs = 1:10, pN = 0.25, pK = 0.08, nExp = nExp_poi, reuse.pANN = FALSE, sct = FALSE)
[1] "Creating 61614 artificial doublets..."
[1] "Creating Seurat object..."
[1] "Normalizing Seurat object..."
Error in NormalizeData.default(object = GetAssayData(object = object,  :
  trying to get slot "params" from an object of a basic class ("NULL") with no slots

whereas if I set it to TRUE, it just runs the sct transform again. 

so <- doubletFinder_v3(so, PCs = 1:10, pN = 0.25, pK = 0.08, nExp = nExp_poi, reuse.pANN = FALSE, sct = TRUE)
[1] "Creating 61614 artificial doublets..."
[1] "Creating Seurat object..."
[1] "Running SCTransform..."
Calculating cell attributes from input UMI matrix: log_umi
Variance stabilizing transformation of count matrix of size 26338 by 246455
Model formula is y ~ log_umi
Get Negative Binomial regression parameters per gene
Using 2000 genes, 5000 cells
  |======================================================================| 100%
Found 149 outliers - those will be ignored in fitting/regularization step

Second step: Get residuals using fitted parameters for 26338 genes
  |=====================                                                 |  30%

**Comment by tkim-NW** [comment]
@nandomgu unlikely you need this anymore but if anyone else comes looking at this thread: if you peep at the code for doubletFinder_v3.R you'll see that doubletFinder_v3() generates artificial doublets and combines them with the seurat object you pass it, and then it runs Seurat's SCTransform() along with RunPCA again on this new object, it's how DoubletFinder does it's doublet detection!! The messages are just letting you know what it's doing at each step. Setting sct = T means the function will run SCTransform() on the new object, and not the other NormalizeData() --> FindVariableFeatures() --> ScaleData() etc way

**Comment by Plasmiddddd** [comment]
This is helpful to me! Thank you!
