### ISSUE TITLE
About the choise of pK

### ISSUE THREAD

**Issue by WeiZhu1998** [chris-mcginnis-ucsf/DoubletFinder#62]
Hi DoubletFinder developer,

I am Wei, thanks for develop such a useful tool. I am curious about the choise of pK, I follow the "best practice" and use BCmvn to choose pK, but the result is a little large, it's about **0.27**(Cell number is about **13k**). I wonder if this pK is too large and it will influence the judgement of doublet. I notice that in the method part you mention large pK(>0.1) will result pANN distribution are associated with low BC and AUC. How can I choose pK if BCmvn result is more than 0.1. Should I use 0.27 or just use 0.1? Thanks a lot!
<img width="358" alt="批注 2020-02-07 225437" src="https://user-images.githubusercontent.com/48512497/74039569-07860a80-49fd-11ea-916b-295430473041.png">

**Comment by JingleW** [comment]
> Hi DoubletFinder developer,
> 
> I am Wei, thanks for develop such a useful tool. I am curious about the choise of pK, I follow the "best practice" and use BCmvn to choose pK, but the result is a little large, it's about **0.27**(Cell number is about **13k**). I wonder if this pK is too large and it will influence the judgement of doublet. I notice that in the method part you mention large pK(>0.1) will result pANN distribution are associated with low BC and AUC. How can I choose pK if BCmvn result is more than 0.1. Should I use 0.27 or just use 0.1? Thanks a lot!
> <img alt="批注 2020-02-07 225437" width="358" src="https://user-images.githubusercontent.com/48512497/74039569-07860a80-49fd-11ea-916b-295430473041.png">

I met the same problem as yours, a bigger mpK than expected. 
Besides, how do you get the plot with the pK value labelled for the X-axis, and BCmetric value for the Y-axis? I run the code "bcmvn_kidney <- find.pK(sweep.stats_kidney)" to get this plot but with no X- or Y-axis labels.  

Thank you very much.

**Comment by WeiZhu1998** [comment]
Hi,
I met the same problem and didn't get axis label, so I write a small script to plot a new one, you can have a reference. But I am still confused about the first question that how can we choose pK if it is a little larger than expected. If you have idea, please share with me, thanks!

pK=as.numeric(as.character(bcmvn_kidney$pK))
BCmetric=bcmvn_kidney$BCmetric
pK_choose = pK[which(BCmetric %in% max(BCmetric))]

par(mar=c(5,4,4,8)+1,cex.main=1.2,font.main=2)
plot(x = pK, y = BCmetric, pch = 16,type="b",
     col = "blue",lty=1)
abline(v=pK_choose,lwd=2,col='red',lty=2)
title("The BCmvn distributions")
text(pK_choose,max(BCmetric),as.character(pK_choose),pos = 4,col = "red")

Best,
Wei

**Comment by JingleW** [comment]
> Hi,
> I met the same problem and didn't get axis label, so I write a small script to plot a new one, you can have a reference. But I am still confused about the first question that how can we choose pK if it is a little larger than expected. If you have idea, please share with me, thanks!
> 
> pK=as.numeric(as.character(bcmvn_kidney$pK))
> BCmetric=bcmvn_kidney$BCmetric
> pK_choose = pK[which(BCmetric %in% max(BCmetric))]
> 
> par(mar=c(5,4,4,8)+1,cex.main=1.2,font.main=2)
> plot(x = pK, y = BCmetric, pch = 16,type="b",
> col = "blue",lty=1)
> abline(v=pK_choose,lwd=2,col='red',lty=2)
> title("The BCmvn distributions")
> text(pK_choose,max(BCmetric),as.character(pK_choose),pos = 4,col = "red")
> 
> Best,
> Wei

Hi, thanks for you script. 
I have no idea on the big pK value. I am waiting for Chris reply.
I noticed that , for the same data, when different resolution values were used in Seurat FindClusters, different pK values were chosen and different Doublets were identified. When a smaller resolution was used (the clusters could be well annotated with mark genes at this resolution), the pK value seemed normal. So, whether a relative smaller resolution could be used for DoubletFinder, then the singlet could be re-clustered with a higher resolution?

**Comment by chris-mcginnis-ucsf** [comment]
Hi JingleW and WeiZhu1998,

Apologies for the delayed response -- I do not check this issues page very often.

And thanks for the script, I'll include the new visualization in the package!

Regarding pK, the value of this parameter will depend on the structure of the data (e.g., number of transcriptionally-distinct cell states present in your system). When I refer to values of pK > 0.1 resulting in poor DoubletFinder performance, this was specifically for the PBMC datasets used in the paper and this rule should not necessarily apply for your own dataset.

The key to determining which pK to use / whether the pK value is too high requires actually looking at your data. Assuming you know which cell states are present in your system and, thus, which clusters have the potential to be doublets, does using the suggested pK value pick out these clusters? Conversely, does the suggested pK value classify cells as doublets that are part of a cluster that you are very confident are singlets? 

Finally, I'm a bit confused by the final message from JingleW, as the pK identification step occurs after running paramSweep, which does not take clustering into account... Could you provide your code?

Chris

**Comment by daihq3** [comment]
how about choose a value of 0.005 or 0.09, who performs better

**Comment by daihq3** [comment]
i see some code that choose the nExp by square of cell number*0.08,is this way okay
