### ISSUE TITLE
paramSweep_v3

### ISSUE THREAD

**Issue by AMaynard10** [chris-mcginnis-ucsf/DoubletFinder#63]
Hello I recently changed the version of Seurat to 3.0. I have the following error and was hoping for some direction.

Error in paramSweep_v3(seurat_objecgt, PCs = 1:20, sct = FALSE) : 
  trying to get slot "counts" from an object of a basic class ("NULL") with no slots

Thanks so much!

**Comment by AMaynard10** [comment]
figure it out :) thanks!

**Comment by grimwoo** [comment]
@AMaynard10 Hi, I used the seurat object from loom file greated by velocyto. And this error occured. Could you let me know how to solve it?
