### ISSUE TITLE
Problem with integrated data due to normalization

### ISSUE THREAD

**Issue by tkapello** [chris-mcginnis-ucsf/DoubletFinder#67]
Hi Chris,

  I tried to use DoubletFinder on one integrated Seurat object and it gives me this error

`Error in NormalizeData.default(object = GetAssayData(object = object,  : 
  trying to get slot "params" from an object of a basic class ("NULL") with no slots`

when I run _paramSweep_v3_. The individual datasets were normalized before the integration. Do you have a good fix?

**Comment by stefanonard85** [comment]
Do you use SCT transform? If yes you have to set sct=TRUE

**Comment by tkapello** [comment]
No, the data were log normalized. I found out that the reason was that _DoubletFinder_ was looking for the normalization slot in the Seurat object which was not available since the datasets were normalized before being integrated. I do not know if it would make sense to write code for integrated datasets so that one does not have to apply _DoubletFinder_ to each of the to-be-integrated datasets one by one... Unless there is a way around?

**Comment by chris-mcginnis-ucsf** [comment]
It's actually importnat NOT to run DoubletFinder on aggregated data but instead on each dataset individually before merging. This ensures that DoubletFinder doesn't try to find doublets that cannot exist (i.e., doublets from cell populations loaded into distinct 10x lanes).
