### ISSUE TITLE
Error in summarizeSweep

### ISSUE THREAD

**Issue by jad362** [chris-mcginnis-ucsf/DoubletFinder#69]
Hi- I'm performing GT = FALSE analysis with sct = TRUE. After running paramsweep_v3, I try to run SummarizeSweep but I keep getting this error:
Error in strsplit(name.vec, split = "pN_") : non-character argument

I'm not sure why I kepe getting this error and I've tried a host of different methods to correct it but I have had no luck. Any help would be greatly appreciated.

**Comment by chris-mcginnis-ucsf** [comment]
Hm, that's strange. Can you post your full code? i.e., including pre-processing and everything upstream of running paramsweep. Are you sure you ran SCTransform on the original Seurat object?
