### ISSUE TITLE
Method for loom objects

### ISSUE THREAD

**Issue by lambdamoses** [chris-mcginnis-ucsf/DoubletFinder#7]
Hi, I just started using your package and it's working great. There's a branch in the Seurat repo that has support for loom objects, so we don't have to load the entire dataset into memory. Right now, Seurat supports normalization, scaling, finding variable genes, PCA, and tSNE for loom objects, so the Seurat pipeline for loom is very similar to that for sparse matrices in memory. Perhaps loom will become more and more common as we're getting more large datasets. However, your package only works for Seurat objects, because `AddMetaData` in Seurat doesn't have a method for loom objects yet; I don't know if a method for loom will be implemented in the near future. The way to add metadata into loom objects is `obj$add.col.attribute`, see [this vignette](https://satijalab.org/seurat/mca_loom.html). Can you write a method of your function for loom objects? Or may I do a pull request?

**Comment by chris-mcginnis-ucsf** [comment]
Hey -- I hadn't thought to implement a version for loom objects, but that seems like a logical next step! We are focusing on reviews right now, but if you want to do a pull request and document an example case we would be very appreciative. I anticipate an if statement referring to the class of the original object will suffice.

**Comment by chris-mcginnis-ucsf** [comment]
Excited to see your implementation -- let me know when you would like to send for review
