### ISSUE TITLE
pK optimization

### ISSUE THREAD

**Issue by tkapello** [chris-mcginnis-ucsf/DoubletFinder#71]
More of a clarification than an issue. I understand that the pK value to use is the peak in the BCmvn plot. However, in my case the curve looks monotonous. Which value would you pick in this case?

[Rplot.pdf](https://github.com/chris-mcginnis-ucsf/DoubletFinder/files/4377762/Rplot.pdf)

**Comment by chris-mcginnis-ucsf** [comment]
Hmmm... I would try the low local minimum, and then perhaps repeat the workflow to see if the set of the artifical doublets you generated happened to just be a bit off...

**Comment by vwtlin** [comment]
@tkapello Thanks for opening this issue. I have the same question as well.

Hi @chris-mcginnis-ucsf, thanks very much for the amazing tool!

What do you mean by "low local minimum"? Do you refer to the peak as attached?
![Rplot](https://user-images.githubusercontent.com/44833405/105967420-c7fa7780-60c0-11eb-87d7-f2d6bfbca2e0.png)

**Comment by CWYuan08** [comment]
Hi @vwtlin, I also have a plot similar to yours, have you figured out which value to use? Many thanks!
