### ISSUE TITLE
Error in summarizeSweep and conceptual question about pN

### ISSUE THREAD

**Issue by evaknichols** [chris-mcginnis-ucsf/DoubletFinder#72]
Hello,

I look forward to using your great tool! Unfortunately I'm experiencing an error, but I'm hoping it's a simple one since I'm still a novice at implementing sc analysis tools. I've been following the "real world" application example you provided. Apologies if I'm missing something obvious.

I have eight batches of data that I will eventually integrate together (in Seurat). For now, I plan to run DoubletFinder individually on each one, remove doublets (after the usual recommended QC steps), then integrate. 

I'm experiencing an error during summarizeSweep for all of the datasets: "NAs introduced by coercionError in seq.default(2, length(name.vec), by = 2) : wrong sign in 'by' argument"

These are the steps I'm following (using one batch as an example; WT_Veh_rep_1 is my Seurat Object):

# Upstream Seurat processing 
WT_Veh_rep_1 <- NormalizeData(WT_Veh_rep_1)
WT_Veh_rep_1 <- ScaleData(WT_Veh_rep_1)
WT_Veh_rep_1 <- FindVariableFeatures(WT_Veh_rep_1, selection.method = "vst", nfeatures = 2000)
WT_Veh_rep_1 <- RunPCA(WT_Veh_rep_1)
WT_Veh_rep_1 <- RunUMAP(WT_Veh_rep_1, dims = 1:15)

# pK identification
sweep.res.list_WT_Veh_rep_1 <- paramSweep_v3(WT_Veh_rep_1, PCs = 1:15, sct = FALSE)
sweep.stats_WT_Veh_rep_1 <- summarizeSweep(WT_Veh_rep_1, GT = FALSE) # errors here

Going back to your paper, I think one possible issue is that maybe I haven't generated the artificial doublets yet (pN). This should require the original filtered RNA/UMI matrices used earlier to generate the Seurat object, right? Am I missing a piece of code that should do that, or is this process taken care of in paramSweep_v3? I have not actually done anything with the matrices themselves....

Thanks for reading and any insight that you have! Happy to provide any other information.

From,
Eva

**Comment by chris-mcginnis-ucsf** [comment]
Hey Eva -- I think you'll just need to use 'sweep.res.list_WT_Veh_rep_1' as the input for summarizeSweep instead of the Seurat object. See the example here:

![image](https://user-images.githubusercontent.com/40582930/78947961-be454c00-7a7b-11ea-8658-92c8f8c8f668.png)

**Comment by chris-mcginnis-ucsf** [comment]
also, if you have any other questions, feel free to reach out to my UCSF email (chris[dot]mcginnis[at]ucsf[dot]edu)

**Comment by evaknichols** [comment]
Thank you, Chris! Sorry to waste your time by overlooking the details in your example.

And, thanks for the email! I might do that. I was looking forward to your webinar on the 28th, but I can't make it because of lab meeting. 

Take care!
Eva

**Comment by chris-mcginnis-ucsf** [comment]
No problem!
