### ISSUE TITLE
Predicted Doublets do not have high UMI counts

### ISSUE THREAD

**Issue by Lesdormis** [chris-mcginnis-ucsf/DoubletFinder#73]
Dear Chris,

Thanks for developing this very helpful tool.
I have some questions hope you can give us help.
Do you think doublets should also have a high UMI counts in it?
After doing a general DoubletFinder pipeline from an unhashtag SCT seurat object. 
I tried to locate the doublets in my sample. But it seems unintuitive to me that the predicted doublets are not gathered around on the high UMI counts cells, but seems to be scattered around all the cells. 
Did you see something similar in your experience?
![image](https://user-images.githubusercontent.com/30546732/79014451-f068b380-7b38-11ea-8483-d5fa6a798692.png)
(nCount_Trans is the nCount_RNA)

And here is my code
```{r}
sweep.res.list <- paramSweep_v3(obj_temp, PCs = 1:15, sct = T)
 sweep.stats <- summarizeSweep(sweep.res.list, GT = FALSE)
  bcmvn <- find.pK(sweep.stats)
  bcmvn$pK <- as.numeric(as.character(bcmvn$pK))
  # find maximum in BCmetric
  pk = bcmvn$pK[which.max(bcmvn$BCmetric)]
    
    # Homotypic Doublet Proportion Estimate
    annotations <- obj_temp@active.ident
  homotypic.prop <- modelHomotypic(annotations)
  nExp_poi <- round(0.05*ncol(obj_temp))
  nExp_poi.adj <- round(nExp_poi*(1-homotypic.prop))
  
  # Run DoubletFinder
  obj_temp <- doubletFinder_v3(obj_temp, PCs = 1:15, pN = 0.25, pK = pk, nExp = nExp_poi.adj, reuse.pANN = FALSE, sct = T)
```

I also have a question might be interesting.
Do you think your algorithm can distinguish doublets caused by technical issue from syncytia caused by biology?

Thanks in  advance!!!

**Comment by chris-mcginnis-ucsf** [comment]
Hi @Lesdormis -- Doublets usually have enriched nUMIs, but not always (especially if some of the cell types in your data naturally have low RNA content). 

However, I also see that you are including cells with very, very low RNA UMIs in your analysis. DoubletFinder performs best after an initial QC workflow has been performed on the data (i.e., to remove low-quality cells marked by high % mitochondrial reads and/or low RNA UMIs). I wonder if the distinction between predicted singlets and doublets would be more clear if you clean your data a bit.

How are the predicted doublets distributed in gene expression space? Have you tried other pK values?

**Comment by Lesdormis** [comment]
Hi @chris-mcginnis-ucsf , thanks for helping me here.
I have already cleaned the data for a little bit. The reason why it had a very, very low RNA UMIs is because we are not using a whole transcriptome single cell sequencing here, like 10X.
We are using the single-cell targeted panel (Rhapsody T-cell targeted panel), it is similar as using a bead for each droplet and capture a cell, but it can only sequence for **500 genes**.
And I agree that the quality of this data is very bad. But we still want to make use of it.

Thanks!

**Comment by chris-mcginnis-ucsf** [comment]
Ah I see. That makes sense -- and likely also results in the difference in nUMIs between true singlets and doublets being smaller than is observed for full-transcriptome sequencing. This could explain why the difference is less apparent in your previous plot (although there is certainly a shift in the mean nUMIs there). 

I think the best bet is to look at where the doublets fall in gene expression space and spot-check to make sure that a cluster you know is singlets is not being erroneously called.
