### ISSUE TITLE
Automatisation for huge number of samples

### ISSUE THREAD

**Issue by AmelZulji** [chris-mcginnis-ucsf/DoubletFinder#77]
Hi Chris,

Thank you for developing DoubletFinder (DF) and for providing constant help!!! 

I am analysing  dataset consisted of more than 30 samples, and would like to run DoubletFinder on it. However, going sample by sample is not very convenient. Do you maybe have any example of helper function/for loop to automatise it?

In addition, does ambient RNA affect performance of DF? Would you recommend removing ambient RNA before running DF (if yes, have you maybe test some of the tools for removing ambient RNA?), or it is better to remove ambient RNA after DF? 

Your help will be greatly appreciated!

Best,
Amel

**Comment by chris-mcginnis-ucsf** [comment]
Hi Amel ( @AmelZulji ),

Good questions! 

(i) Sounds like a very interesting dataset! There are certain steps that are difficult to automate around (e.g., pK selection), but there are others that you can write an easy for loop to run. For example:

(Assuming you have a list of pre-processed Seurat objects named 'seu_list' that were processed with SCTransform)

```R
sweep.stats.list <- list()
for (i in 1:length(seu_list)) {
  seu_temp <- seu_list[i]
  sweep.res.list <- paramSweep_v3(seu_temp, PCs = seu_temp@commands$RunUMAP.SCT.pca$dims, sct = TRUE)
  sweep.stats <- summarizeSweep(sweep.res.list, GT = FALSE)
  sweep.stats.list[[i]] <- sweep.stats
}
```

**Comment by AmelZulji** [comment]
Hi Chris,

Thank you a lot for helping! 

Amel

**Comment by halterc** [comment]
Hi Chris. Might it be an interesting idea to combine this with "chooseR" to also automate the pK selection process?

**Comment by victorcat4** [comment]
Hey, I was looking at this issue and found here a full script to do exactly that. Here is the link : https://rpubs.com/kenneditodd/doublet_finder_example
