### ISSUE TITLE
Any recommendations about using ground truth datas?

### ISSUE THREAD

**Issue by mesnger** [chris-mcginnis-ucsf/DoubletFinder#79]
Hello, Chris.
Thanks for the great work, and all the updates.

I am working on a pooled single cell data and would like to remove doublets with demuxlet and doubletfinder.

Would you recommend,
A) Remove doublets detected with demuxlet prior to doubletfinder, and try to remove doublets formed by the same person? (adjusting the doublet rate for nExp_poi)
B) Use demuxlet doublet calls as ground truth data and use it as a reference for other doublets
C) Run demuxlet and doubletfinder separately, and choose cells called singlet by both analysis

I reason that C would be the most safe bet, but would like to get some opinion. Also, I could not find  the input format for GT.calls when calling with ground truth data. Could you add some explanations to the function?

Thanks.
JY

**Comment by chris-mcginnis-ucsf** [comment]
Hi @mesnger ,

I think a combo of B and C is best. The ground truth demuxlet calls will aid in DoubletFinder parameter selection (it doesn't force doublet calls, just helps delineate a proper pK for your data). Then I would interrogate which clusters/cells are called by both pipelines to finalize your results.

I will update the GT.calls info -- FYI the correct format would be a column in your Seurat metadata consisting of either "Singlet" or "Doublet"

Chris
