### ISSUE TITLE
"clusteringresults" - vetted annotations or graph-based clusters

### ISSUE THREAD

**Issue by HypoChloremic** [chris-mcginnis-ucsf/DoubletFinder#80]
in the following snippet: 
```
## Homotypic Doublet Proportion Estimate -------------------------------------------------------------------------------------
homotypic.prop <- modelHomotypic(annotations)           ## ex: annotations <- seu_kidney@meta.data$ClusteringResults
nExp_poi <- round(0.075*length(seu_kidney@cell.names))  ## Assuming 7.5% doublet formation rate - tailor for your dataset
nExp_poi.adj <- round(nExp_poi*(1-homotypic.prop))
```
you write that `# ex: annotations <- seu_kidney@meta.data$ClusteringResults`. Are these clusteringresults vetted annotations (e.g. they have been assigned celltype based on marker genes), or can they be graph-based clusters?

**Comment by HypoChloremic** [comment]
I just found a similar issue from some months ago. 
Duplicate of issue #25, however it may be good to clarify this aspect in `README.md`

**Comment by chris-mcginnis-ucsf** [comment]
Will clarify -- thanks! They are vetted annotations.
