### ISSUE TITLE
`ScaleData` before `FindVariableFeatures`

### ISSUE THREAD

**Issue by HypoChloremic** [chris-mcginnis-ucsf/DoubletFinder#81]
```
## Pre-process Seurat object (standard) --------------------------------------------------------------------------------------
seu_kidney <- CreateSeuratObject(kidney.data)
seu_kidney <- NormalizeData(seu_kidney)
seu_kidney <- ScaleData(seu_kidney)
seu_kidney <- FindVariableFeatures(seu_kidney, selection.method = "vst", nfeatures = 2000
```
In `README.md`, you scale before finding the highly variable genes. This order of callbacks differs from the "standard" workflow presented in Seurat. False positive rates should increase if scaling is done before finding variable features. 

Is there some logic behind this?

**Comment by chris-mcginnis-ucsf** [comment]
Good catch! I'm not sure whether this severely impacts DoubletFinder results, but I will update the readme. 

Chris
