### ISSUE TITLE
Using Principle Components correlated with sequencing depth 

### ISSUE THREAD

**Issue by RegnerM2015** [chris-mcginnis-ucsf/DoubletFinder#82]
Chris,

Often one of the first few PCs in single-cell correlates with sequencing depth. This offers justification to ignore this PC when constructing the UMAP/t-SNE plot. 

For example, I have this dataset where PC 2 is correlated with sequencing depth: 

![seq_depth_cor_1_10_noregress(1)](https://user-images.githubusercontent.com/54336249/82838579-a7777f00-9e9a-11ea-8bd4-66bf0c4f439c.png)
 
Do you advise that I run DoubletFinder on the first 10 PCs (1:10)? Alternatively, to ignore the the effect of sequencing depth, I could run DoubletFinder on PCS 1 and 3:11. 

Perhaps this technical variation in sequencing depth is relevant to doublet detection? What are your thoughts?

**Comment by chris-mcginnis-ucsf** [comment]
Hi @RegnerM2015 ,

By sequencing depth, do you mean numbers of UMIs? Even if it is total reads, it is possible that this correlation is biological -- e.g., if one of your cell types has naturally high or low RNA content relative to the other cell types, then you would expect PCs to correlate with total UMIs and/or reads. 

With that being said, I would advise running DoubletFinder with both sets of PCs and comparing the results. Tough to say which would be 'better' without seeing the results first-hand.

Chris
