### ISSUE TITLE
Crashes with Large dataset? Any suggestions?

### ISSUE THREAD

**Issue by Sa753** [chris-mcginnis-ucsf/DoubletFinder#83]
Dear Chris,

I am using your nicely developed doublet finder V3 for single-cell RNA data and is working well for up to 15k cells and also for integated Seurat objects. My problem is that it crashes with larger number of cells. I tried it few time on a dataset of 36k but unfortunately it crashes R and sometimes the whole computer.

I use Mac Catalina 10.15. R version 4.0.0 Seurat V3.

Thanks

**Comment by chris-mcginnis-ucsf** [comment]
Hi @Sa753 ,

Sorry to hear you are having troubles! Assuming that the 36K cells are from multiple scRNAseq libraries, it is worth noting that it is best to run DoubletFinder on each library (e.g., 10x lane) separately.

In case that you are still running into issues, another suggestion would be to normalize using the standard Seurat pipeline (i.e., NOT SCTransform), as SCTransform is a bit more memory-intensive.

Let me know if this works!
Chris
