### ISSUE TITLE
removal of doublets

### ISSUE THREAD

**Issue by rubinaasharmaa** [chris-mcginnis-ucsf/DoubletFinder#84]
Hi,
after running doublet finder script, I can see the doublets in my data but my concern is how are they removed. as I did not see any removal of doublets (but can only identify them).

**Comment by hhaochen** [comment]
same question

**Comment by vincr04** [comment]
Indeed you have to remove them yourself. Otherwise it would be called DoubletRemover ;)
In Seurat you can do
`object_NoDoublets <- subset(object, subset = DF.classification == "Singlet")`

**Comment by rubinaasharmaa** [comment]
> Indeed you have to remove them yourself. Otherwise it would be called DoubletRemover ;)
> In Seurat you can do
> object_NoDoublets <- subset(object, subset = DF.classification == "Singlet")

Thanks but I get this error after running this code.

OM22_NoDoublets <- subset(OM22, subset = DF.classification_0.25_0.03_270 == "Singlet")

Error in FetchData(object = object, vars = unique(x = expr.char[vars.use]),  : 
  None of the requested variables were found:

**Comment by chris-mcginnis-ucsf** [comment]
Hi @rubinaasharmaa and @hhaochen ,

You do have to manually remove the doublets. Assuming the doublet calls are stored in a seurat object named 'seu' in the metadata column called "DF.classification", then you should do the following:

seu_clean <- SubsetData(seu, cells=rownames(seu@meta.data)[which(seu@meta.data$DF.classification == "Singlet")])

Let me know if this works!
Chris

**Comment by Jayjay601** [comment]
Hi Chris,

Would you suggest re-running the normalization step, run pca and etc after removing the doublets because the normalized data, scaled data that are stored in the Seurat object after Seurat and DoubletFinder might affected by the doublets that are going to be removed?

Thank you,

J

**Comment by laijen000** [comment]
Hi @chris-mcginnis-ucsf and @Jayjay601 , 

I have the same question! Should we re-run runPCA, runUMAP, FindNeighbors after removing the doublets from the seurat object? I was also thinking that the doublets may affect clustering so it may make sense to re-cluster after removing them. When I do so, the UMAP plot changes but the major cell types identified remains the same. 

Thank you for your thoughts on this!

**Comment by Statekeylablin** [comment]
@laijen000 and @chris-mcginnis-ucsf，
We run Doubletfinder for 5 samples individually after standard Seurat workflow. Shall we re-run Normalization, ..., PCA after merging 5 samples?

Thank you,

Lin

**Comment by NJU-Bio-Info** [comment]
I also have the same problem as @Jayjay601 @laijen000 and @Statekeylablin described above, can you @chris-mcginnis-ucsf give us some advice?

**Comment by Ajaingithub** [comment]
I also have same question. Please advice @chris-mcginnis-ucsf .

**Comment by NJU-Bio-Info** [comment]
From my perspective, I think we can select the remain single cell to create a new seurat object.

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："Abhinav&nbsp;Jain ***@***.***&gt;;
发送时间：2022年1月19日(星期三) 凌晨0:03
收件人："chris-mcginnis-ucsf/DoubletFinder" ***@***.***&gt;;
抄送："NJU-BIO-Infor ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [chris-mcginnis-ucsf/DoubletFinder] removal of doublets (#84)
-----------------------------------

 

 
I also have same question. Please advice @chris-mcginnis-ucsf .
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by quaxxo** [comment]
Same question here... Thanks for your help!

**Comment by olneykimberly** [comment]
same question! Thanks :)
