### ISSUE TITLE
Error in NormalizeData.default running DoubletFinder on an integrated seurat object in R

### ISSUE THREAD

**Issue by SebRW** [chris-mcginnis-ucsf/DoubletFinder#85]
I'm trying to run DoubletFinder on a seurat object resulting from the integration of various datasets.

The Seurat object has 2 assays: RNA & integrated.

The integrated seurat object have been fully processed:

-Normalization and FindVariableFeature pre-integration

-ScaleData, RunPCA, FindNeighbors, FindClusters, RunUMAP on the integrated object.

The paramSweep_v3() function of DoubletFinder gives the following output:

```
sweep.res.list <- paramSweep_v3(integrated.seu, PCs = 1:38, sct = FALSE)
Loading required package: fields
Loading required package: spam
Loading required package: dotCall64
Loading required package: grid
Spam version 2.5-1 (2019-12-12) is loaded.
Type 'help( Spam)' or 'demo( spam)' for a short introduction 
and overview of this package.
Help for individual functions is also obtained by adding the
suffix '.spam' to the function name, e.g. 'help( chol.spam)'.

Attaching package: ‘spam’

The following object is masked from ‘package:R.utils’:

    cleanup

The following objects are masked from ‘package:base’:

    backsolve, forwardsolve

Loading required package: maps
See https://github.com/NCAR/Fields for
 an extensive vignette, other supplements and source code 
[1] "Creating artificial doublets for pN = 5%"
[1] "Creating Seurat object..."
[1] "Normalizing Seurat object..."
Error in NormalizeData.default(object = GetAssayData(object = object,  : 
  trying to get slot "params" from an object of a basic class ("NULL") with no slots
```

Why does this indicate there are no slots in my Seurat object?

**Comment by chris-mcginnis-ucsf** [comment]
Hi @SebRW ,

You should run DoubletFinder on the data before integration. Let me know if you run into the same error.

Chris

**Comment by mcsimenc** [comment]
Hi Chris,

I'm facing the same issue of wanting to run DoubletFinder on an integrated Seurat object. According to the [Seruat tutorial on data integration](https://satijalab.org/seurat/v3.0/integration.html), RunPCA, FindNeighbors, FindClusters, and RunTSNE are meant to be run after the integration step. Is there any way to run DoubletFinder on the integrated object?

Thanks!

Matt

**Comment by chris-mcginnis-ucsf** [comment]
Hi Matt,

I'm not going to add support for running DoubletFinder on integrated Seurat objects, because I think this could lead to users employing the method incorrectly if they do not understand why DoubletFinder should often be run on individual 10x datasets (e.g., to avoid 'looking' for doublets that couldn't actually exist in the data).

One case where it would be OK to run DoubletFinder on an integrated Seurat object is if all of the datasets being integrated are technical replicates. This would ensure that any doublets predicted by DoubletFinder actually have the chance of existing. However, if this was the case, you really wouldn't need to use the integration and label transfer workflow anyways (read-depth normalization should suffice). If you want to apply DoubletFinder to an integrated dataset, I would recommend running DoubletFinder on each pre-integrated dataset independently, and then merging the results.

Chris
________________________________

**Comment by mcsimenc** [comment]
Thanks for the explanation, Chris!

**Comment by laijen000** [comment]
Hi @chris-mcginnis-ucsf , 
Thank you for this tool! I am running DoubletFinder on each individual Seurat object prior to integration. However I was wondering whether you would recommend removing the doublets from each object prior to integration, or later in downstream analyses? 

For example, between doubletFinder_v3() and SelectIntegrationFeatures() steps, should I subset each seurat object to remove the doublets?

Thank you

**Comment by HuangJipen** [comment]
> Hi @SebRW ,
> 
> You should run DoubletFinder on the data before integration. Let me know if you run into the same error.
> 
> Chris

Hi Chris,

I encountered the same issue. Initially, I integrated two datasets and attempted to run DoubletFinder, but it resulted in an error: `"Error in NormalizeData.default(object = GetAssayData(object = object, : trying to get slot 'params' from an object of a basic class ('NULL') with no slots."` 
Following your response, I attempted to run DoubletFinder before integrating the data. I individually applied NormalizeData, ScaleData, FindVariableFeatures, RunPCA, FindNeighbors, FindClusters, and RunUMAP on each single dataset. However, I am still encountering the same error: "Error in NormalizeData.default(object = GetAssayData(object = object, : trying to get slot 'params' from an object of a basic class ('NULL') with no slots." Could you please advise on which step might be causing the issue? Below is the code for processing a single sample:
Sug_virgin <- subset(Sug_virgin, subset = nFeature_RNA > 300 & nFeature_RNA < 4500 & percent.mt < 10)
dim(Sug_virgin)

```
all.genes <- rownames(Sug_virgin)
Sug_virgin <- NormalizeData(Sug_virgin)
Sug_virgin <- ScaleData(Sug_virgin, features = all.genes)
Sug_virgin <- FindVariableFeatures(Sug_virgin, nfeatures = 4000)
Sug_virgin <- RunPCA(Sug_virgin, features = VariableFeatures(Sug_virgin))

Sug_virgin <- FindNeighbors(Sug_virgin, reduction = "pca", dims = 1:30)
Sug_virgin <- FindClusters(Sug_virgin, resolution = 0.1)
Sug_virgin <- RunUMAP(Sug_virgin, reduction = "pca", dims = 1:30)

sweep.res.list_kidney <- paramSweep(Sug_virgin, PCs = 1:30, sct = FALSE)
[1] "Creating artificial doublets for pN = 5%"
[1] "Creating Seurat object..."
[1] "Normalizing Seurat object..."
Error in NormalizeData.default(object = GetAssayData(object = object,  : 
  trying to get slot "params" from an object of a basic class ("NULL") with no slots
```
Is there a specific step in this process that might be causing the error? Thanks
                                                                                                                                    Jipeng
