### ISSUE TITLE
Regressing out Total nUMI (nCount_RNA) during scaling 

### ISSUE THREAD

**Issue by RegnerM2015** [chris-mcginnis-ucsf/DoubletFinder#87]
Hi @chris-mcginnis-ucsf ,

To my understanding, if I want to regress out total RNA content (nCount_RNA) during scaling, I would do so before running `doubletFinder_v3`:
![image](https://user-images.githubusercontent.com/54336249/85494877-855f4280-b5a7-11ea-9490-e3543fa1a91e.png)

However, how would this work for parameter sweeping to find the optimal pK value? Would I input this nCount_RNA-regressed Seurat object into `paramSweep_v3`? If so, would I have to manipulate the source code of `paramSweep_v3` to change the underlying `ScaleData` step which does not implement any form of regressions. 

As a summary, which approach is more appropriate: 

## Option 1 using unmodified `paramSweep_v3` : 
##Pre-process Seurat object (standard) --------------------------------------------------------------------------------------
seu_kidney <- CreateSeuratObject(kidney.data)
seu_kidney <- NormalizeData(seu_kidney)
seu_kidney <- FindVariableFeatures(seu_kidney, selection.method = "vst", nfeatures = 2000)
seu_kidney <- ScaleData(seu_kidney,vars.to.regress = "nCount_RNA")
seu_kidney <- RunPCA(seu_kidney)
seu_kidney <- RunUMAP(seu_kidney, dims = 1:10)

 ##pK Identification (no ground-truth) ---------------------------------------------------------------------------------------
sweep.res.list_kidney <- paramSweep_v3(seu_kidney, PCs = 1:10, sct = FALSE)
sweep.stats_kidney <- summarizeSweep(sweep.res.list_kidney, GT = FALSE)
bcmvn_kidney <- find.pK(sweep.stats_kidney)

 ##Run DoubletFinder without homotypic adjustment and optimal pK of 0.09
seu_kidney <- doubletFinder_v3(seu_kidney, PCs = 1:10, pN = 0.25, pK = 0.09, nExp = nExp_poi, reuse.pANN = FALSE, sct = FALSE)

## Option 2 using modified/custom `paramSweep_v3`:
##Pre-process Seurat object (standard) --------------------------------------------------------------------------------------
seu_kidney <- CreateSeuratObject(kidney.data)
seu_kidney <- NormalizeData(seu_kidney)
seu_kidney <- FindVariableFeatures(seu_kidney, selection.method = "vst", nfeatures = 2000)
seu_kidney <- ScaleData(seu_kidney,vars.to.regress = "nCount_RNA")
seu_kidney <- RunPCA(seu_kidney)
seu_kidney <- RunUMAP(seu_kidney, dims = 1:10)

##pK Identification (no ground-truth) with **custom** `paramSweep_v3` that regresses out nCount_RNA during ScaleData
sweep.res.list_kidney <- **paramSweep_v3_custom**(seu_kidney, PCs = 1:10, sct = FALSE)
sweep.stats_kidney <- summarizeSweep(sweep.res.list_kidney, GT = FALSE)
bcmvn_kidney <- find.pK(sweep.stats_kidney)

##Run DoubletFinder without homotypic adjustment and optimal pK of 0.09
seu_kidney <- doubletFinder_v3(seu_kidney, PCs = 1:10, pN = 0.25, pK = 0.09, nExp = nExp_poi, reuse.pANN = FALSE, sct = FALSE)

**Comment by chris-mcginnis-ucsf** [comment]
Hi @RegnerM2015 ,

I tested whether nUMI regression influenced DoubletFinder results when developing the method and found that it had basically no effect. Considering that, along with (i) that nUMI regression can take really long and (ii) that parameter estimation requires iterative pre-processing, I decided to not include it in the pipeline. 

With that being said, you can still do nUMI regression when pre-processing your real data (i.e., not containing artificial doublets) if you like. I've just found that it didn't influence doublet prediction results when applied to PBMCs -- but this could not be the case for all data. 

Chris
