### ISSUE TITLE
paramSweep_v3 takes too long on Seurat SCT transformed data

### ISSUE THREAD

**Issue by liuweihanty** [chris-mcginnis-ucsf/DoubletFinder#90]
Hi there the developers for doubletFinder, thanks for the wonderful tool! I was running this step on my SCT transformed Seurat object(~10000 cells and 2000 features)

sweep.res.list_kon1 <- paramSweep_v3(seu, PCs = 1:10, sct = TRUE) .

But the program runs for too long, I left it to run overnight and the progress bar is only 12%...and it has warning message like this: 
100%non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.500000non-integer x = 0.5

I've tried to reduced the number of principal components when I run PCA and UMAP dimension reduction but it didn't help. Previously I've successfully run DoubletFinder on my seurat object using the standard normalization workflow by Seurat thought.

DO you have any thoughts? Thanks so much!

**Comment by chris-mcginnis-ucsf** [comment]
Hi @liuweihanty ,

If you're running into computing power issues, I would just run the DoubletFinder steps on a Seurat object not pre-processed using SCTransform (e.g., using the standard NormalizeData -> ScaleData -> etc. workflow). SCTransform is a lot slower than the standard workflow, and while I haven't tested this explicitly, my sense is that the results would not differ significantly.   

Chris
