### ISSUE TITLE
Using the first 50 PCs for DoubletFinder 

### ISSUE THREAD

**Issue by RegnerM2015** [chris-mcginnis-ucsf/DoubletFinder#91]
Hi @chris-mcginnis-ucsf ,

I understand it's recommended to input the "statistically significant" PCs into DoubletFinder. Often times the ElbowPlots show 10-15 dims. However, would it be more unbiased/inclusive to just include all 50 PCs? Would using all 50 negatively affect performance? 

Just wanted to hear your thoughts! Thanks

Best,
Matt

**Comment by chris-mcginnis-ucsf** [comment]
Hi @RegnerM2015 ,

I haven't compared results of using normal vs all PCs, but my sense is that using all of the PCs would negatively influence performance. You should try it on your data and see how the results compare.

Chris

**Comment by RegnerM2015** [comment]
Thanks Chris!

I tried this out on my data by running DoubletFinder with two different nPCs parameters (50 and 10) on the same Seurat object.

With my specified doublet rate, I call 262 doublets in both cases. There are 167 doublet calls shared between them.

The pK for the  10 PC iteration is 0.04 and the pK for the 50 PC iteration is  0.005. 

Would I conclude, that it is acceptable to proceed with 50 PCs? Thanks for the help.

**Comment by chris-mcginnis-ucsf** [comment]
hey @RegnerM2015 ,

You can't really conclude much from the information provided. The key test is to actually look at the doublets that are being called by both approaches. Are they the same or different? Based on your knowledge about your biological system, do one of the sets of predictions seem more accurate?

**Comment by RegnerM2015** [comment]
Hi @chris-mcginnis-ucsf ,

Do you mean looking at the barcodes of the predicted doublets in each approach?

If so, then yes I compute the intersection of PC50 doublet barcodes with PC10 doublet barcodes:
```


> head(DF.PC50.doublets)
[1] "AAACGAATCAAGATAG-1" "AAAGAACCAGAAGTTA-1" "AAAGGTACAACATCGT-1"
[4] "AAAGTGAAGCCGAACA-1" "AACAAAGCATGCCGAC-1" "AACAAGACACAGCCAC-1"
> head(DF.PC10.doublets)
[1] "AAACGAATCAAGATAG-1" "AAAGGTACAACATCGT-1" "AACAAAGCATGCCGAC-1"
[4] "AACAACCGTGCACAAG-1" "AACACACAGCCGTTGC-1" "AACACACAGTAAAGCT-1"

> length(intersect(DF.PC50.doublets,DF.PC10.doublets))
[1] 167
```

Meaning that both approaches call the same 167 barcodes as doublets. Below I look at the nFeature_counts variable startified by each doublet approach. DoubletFinder with 50 PCs is on top. DoubletFinder with 10 PCs is on the bottom:

![50PCs_FeatureCounts](https://user-images.githubusercontent.com/54336249/92803920-e36d1c00-f385-11ea-989c-b62678de8498.PNG)
![10PCs_FeatureCounts](https://user-images.githubusercontent.com/54336249/92803921-e405b280-f385-11ea-9368-eee81fb8fdb0.PNG)

**Comment by chris-mcginnis-ucsf** [comment]
So it looks like adding the extra PCs doesn't add too much information, but also doesn't screw up the results. Good to know!

**Comment by RegnerM2015** [comment]
What would I look for if adding the extra PCs negatively affected performance? Would it call more cells that just have higher feature counts or RNA content? 

In other words, how do you know when you "screwed up" the results?
