### ISSUE TITLE
Obtain different pK values when rerun paramSweep_v3

### ISSUE THREAD

**Issue by 06smile** [chris-mcginnis-ucsf/DoubletFinder#92]
Hi, chris-mcginnis-ucsf,

Thanks for developing the great tool!

After processing my single cell data obtained from several independent experiments following the standard Seurat flow, I then subset the data to obtain one experiment and saved as a new Seurat object. I then used this new Seurat object in "paramSweep_v3, summarizeSweep and find.pK" analyses. The pK value corresponds to the maximum of BCmetric is 0.005.  However, when I rerun this "paramSweep_v3, summarizeSweep and find.pK analyses" analyses, the pK values are different from previous analyses and the pK corresponding to the maximum of BCmetric is now 0.26. And the pK goes back 0.005 if I rerun the scripts from data subset followed by paramSweep_v3.

Would you please help to explain this? Which pK value should I use for downstream DoubletFinder analysis?

Thanks a lot.

Siming

**Comment by Sergio-ote** [comment]
Hi, I have the same issue and I have no idea of why this occurs. Also, in my case, the 0.005 is consistent in some samples, and it looks weird to me because I have the sense that something is going on.

**Comment by chris-mcginnis-ucsf** [comment]
Hi all -- the pK estimation step can be a bit variable at times. If all of your different datasets are technical replicates, I would suggest applying a single pK value to all of your datasets. If the datasets are actually different, I would use the distinct pK values you get.

**Comment by yoavhadas** [comment]
Hi Chris
I have a similar issue. In my case, I run find.pK analysis on the same Seurat object, and every time I get a different graph and the pK corresponding to the maximum of BCmetric varies greatly
