### ISSUE TITLE
doubletFinder error 

### ISSUE THREAD

**Issue by wuzhigui** [chris-mcginnis-ucsf/DoubletFinder#95]
![image](https://user-images.githubusercontent.com/70992194/99224946-2cc46680-2822-11eb-8ca6-708b0a427bfd.png)
Hello ! I'm sorry to bother you with my question .
The above picture is my seuratobj ,pbmc . 
When i run 
`pbmc <- doubletFinder(pbmc, PCs = 1:10, pN = 0.25, pK = 0.09, nExp = nExp_poi, reuse.pANN = F)
pbmc <- doubletFinder(pbmc, PCs = 1:10, pN = 0.25, pK = 0.09, nExp = nExp_poi.adj, reuse.pANN = "pANN_0.25_0.09_913")
`
I got this error ,
`Error in is.data.frame(x) : "data"槽名不存在于"Seurat"类别对象中`
How can i figure out it ? 
Please help me ! Thanks again !

**Comment by chris-mcginnis-ucsf** [comment]
Hi @wuzhigui ,

Does the first command with reuse.pANN=F work?

Chris
