### ISSUE TITLE
paramSweep_v3 error: invalid type or length for slot name

### ISSUE THREAD

**Issue by levinhein** [chris-mcginnis-ucsf/DoubletFinder#96]
The final error during the **paramSweep_v3 error()** run is **Error in slot(object = object, name = slot) :    invalid type or length for slot name**

```

 ## pK Identification (no ground-truth) --------------------------------------------------------------------------------------- > sweep.res.TCS<- paramSweep_v3(TCS, PCs = 1:10, sct = FALSE) 
[1] "Creating artificial doublets for pN = 5%" [1] "Creating Seurat object..." 
[1] "Normalizing Seurat object..." 
Performing log-normalization 
0%   10   20   30   40   50   60   70   80   90   100% 
[----\|----\|----\|----\|----\|----\|----\|----\|----\|----\| 
**************************************************\| 
[1] "Finding variable genes..." 
Calculating gene variances 
0%   10   20   30   40   50   60   70   80   90   100% 
[----\|----\|----\|----\|----\|----\|----\|----\|----\|----\| 
**************************************************\| 
Calculating feature variances of standardized and clipped values 
0%   10   20   30   40   50   60   70   80   90   100% 
[----\|----\|----\|----\|----\|----\|----\|----\|----\|----\| 
**************************************************\| 
[1] "Scaling data..." 
Error in slot(object = object, name = slot) :    invalid type or length for slot name

```

![image](https://user-images.githubusercontent.com/68268222/99504759-ed7d4d80-29ba-11eb-8e4a-0667c13efa78.png)

**Comment by chris-mcginnis-ucsf** [comment]
Hi @levinhein ,

Can you provide more code describing how you generated the "TCS" Seurat object?

Chris

**Comment by cwarden45** [comment]
I am not sure why, but I had to keep running `install_github('chris-mcginnis-ucsf/DoubletFinder', force=TRUE)` to regain access to the `doubletFinder()` function (and I never could see the `doubletFinder_v3()` function).

However, I encountered that same error message when I was trying to prepared a processed Seurat file to DoubletFinder, assuming that I have to run the `NormalizeData()`, `FindVariableFeatures()`, `ScaleData()`, and `RunPCA()` functions from Seurat before running DoubletFinder.

So, if that is the problem for others, then I found a possible solution.

*I suspect there should be an easier way that uses fewer lines of code.*  However, you can see the example that I have provided below that runs with **0 error messages at the paramSweep_v3 (or earlier Seurat commands)**:.

```
library(DropletUtils)

sampleID = "[sampleID]"
count_dir_10x = "/path/to/outs/filtered_feature_bc_matrix"
max.pc = 20
prop.doublets = 0.2

sce = read10xCounts(count_dir_10x)
sce_counts = counts(sce)
sce_counts = as.matrix(sce_counts)

library(Seurat)
colnames(sce_counts) = colData(sce)$Barcode
meta.table = data.frame(Sample=colData(sce)$Barcode)
rownames(meta.table) = colData(sce)$Barcode
sce2 = CreateSeuratObject(sce_counts, project="DoubletFinder",min.cells = 3,
					min.genes = 2000, is.expr=1, meta.data = meta.table)
print(dim(sce2))

sce2 = NormalizeData(sce2)
sce2 = FindVariableFeatures(sce2)
sce2 = ScaleData(sce2)
sce2 = RunPCA(sce2)

sce2=JackStraw(sce2, prop.freq=0.1)
sce2=ScoreJackStraw(sce2, dims = 1:20)
JackStrawPlot(sce2, dims = 1:20)
library(ggplot2)
ggsave(paste(sampleID,"-Seurat_sig_PCA_plot.png",sep=""))

print(dim(sce2))

#stop()

library(DoubletFinder)

#based upon https://github.com/xnnba1984/DoubletCollection/blob/master/R/FindDoublets.R
sweep.vector = paramSweep_v3(sce2, PCs = 1:max.pc, sct = FALSE)
sweep.table = summarizeSweep(sweep.vector)
png(paste(sampleID,"-DoubletFinder-find.pK-BCmvn.png",sep=""))
bcmvn = find.pK(sweep.table)
dev.off()

pK = bcmvn$pK[which.max(bcmvn$BCmetric)]
pK = as.numeric(levels(pK))[pK]

sce2 = DoubletFinder::DoubletFinder(sce2,PCs = 1:max.pc, pK = pK, nExp = round(ncol(sce2) * prop.doublets))
```

In the process of running that script, I also lost access to the DoubletFinder() function.  However, I am going to try saving the intermediate files as .Rdata for the session to enable resuming running after the error message at the last step.  If I still have issues, then I will submit a new ticket.

In the meantime, I hope that the code above might be helpful for others who encountered the error message for this ticket!
