### ISSUE TITLE
Seurat 4 compatability?

### ISSUE THREAD

**Issue by Dazcam** [chris-mcginnis-ucsf/DoubletFinder#97]
Hi there,

I was wondering if Doublet Finder was compatible with Seurat 4? If not, are you planning any updates in the near future to make it possible to incorporate data generated in Seurat 4 with Doublet Finder. 

I read there were some [minor changes](https://satijalab.org/seurat/v4_changes.html) to differential expression log-fold calculations in the FindVariables() function between Seurat versions.

Many Thanks,

Darren

**Comment by chris-mcginnis-ucsf** [comment]
Hi Darren,

This is on my to-do list. Will release an updated version once I get around to it.

Chris
