### ISSUE TITLE
two peaks of the pk distribution

### ISSUE THREAD

**Issue by ling-lyang** [chris-mcginnis-ucsf/DoubletFinder#99]
Hi Chris, 

I'm running doubletfinder on a single sample of 20k cells without ground truth.
I got a distribution of two peaks, one around 0.03, and another very high one at 0.3, and it's likely to continue going up beyond 0.3.

Should I set pk at 0.03 or 0.3? 

Cells with high mt.perc (>20%) and high nCounts (>6000) has been removed. 

Thanks!
Ling

**Comment by chris-mcginnis-ucsf** [comment]
Hi @ling-lyang ,

Unfortunately there's no "clean" answer to this -- your best bet is to look at the DoubletFinder results from both pK values and make your best judgement as to which one is correct. In my experience, the lower pK values are usually more accurate.

Chris
